import { SyncedLyricLine } from './types';

export interface LyricLanguage {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LYRIC_LANGUAGES: LyricLanguage[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'tl', name: 'Filipino', nativeName: 'Tagalog', flag: '🇵🇭' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'zh', name: 'Chinese', nativeName: '中文 (简体)', flag: '🇨🇳' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
];

/**
 * Pre-compiled multilingual synchronized lyrics for all songs in Sonora.
 * Each language entry maintains EXACT matching timestamps with the original song.
 */
export const CATALOG_LYRICS_DB: Record<string, Record<string, SyncedLyricLine[]>> = {
  // 1. Stay (feat. Mikky Ekko) - Rihanna
  'song-1788809484263': {
    en: [
      { time: 0, text: '♪ (Gentle piano intro) ♪' },
      { time: 10, text: 'All along, it was a fever' },
      { time: 14, text: 'A cold sweat, hot-headed believer' },
      { time: 19, text: "I threw my hands in the air, said, 'Show me somethin''" },
      { time: 25, text: "He said, 'If you dare, come a little closer'" },
      { time: 31, text: "'Round and around and around and around we go" },
      { time: 37, text: 'Oh, now, tell me now, tell me now, tell me now you know' },
      { time: 43, text: 'Not really sure how to feel about it' },
      { time: 48, text: 'Somethin\' in the way you move' },
      { time: 53, text: "Makes me feel like I can't live without you" },
      { time: 59, text: 'It takes me all the way' },
      { time: 64, text: 'I want you to stay' },
      { time: 72, text: "It's not much of a life you're livin'" },
      { time: 77, text: "It's not just something you take, it's given" },
      { time: 83, text: "'Round and around and around and around we go" },
      { time: 89, text: 'Oh, now, tell me now, tell me now, tell me now you know' },
      { time: 95, text: 'Not really sure how to feel about it' },
      { time: 100, text: 'Something in the way you move' },
      { time: 106, text: "Makes me feel like I can't live without you" },
      { time: 111, text: 'It takes me all the way' },
      { time: 117, text: 'And I want you to stay' },
      { time: 123, text: 'Ooh, the reason I hold on' },
      { time: 129, text: "'Cause I need this hole gone" },
      { time: 135, text: "Funny you're the broken one" },
      { time: 139, text: "But I'm the only one who needed savin'" },
      { time: 144, text: "'Cause when you never see the light" },
      { time: 148, text: "It's hard to know which one of us is cavin'" },
      { time: 153, text: 'Not really sure how to feel about it' },
      { time: 158, text: 'Somethin\' in the way you move' },
      { time: 163, text: "Makes me feel like I can't live without you" },
      { time: 168, text: 'It takes me all the way' },
      { time: 173, text: 'I want you to stay... stay' },
    ],
    es: [
      { time: 0, text: '♪ (Intro suave de piano) ♪' },
      { time: 10, text: 'Todo este tiempo, fue una fiebre' },
      { time: 14, text: 'Un sudor frío, una creyente apasionada' },
      { time: 19, text: "Lancé mis manos al aire y dije: 'Muéstrame algo'" },
      { time: 25, text: "Él dijo: 'Si te atreves, acércate un poco más'" },
      { time: 31, text: 'Vueltas y vueltas y vueltas damos sin parar' },
      { time: 37, text: 'Oh, dime ahora, dime ahora, dime si ya lo sabes' },
      { time: 43, text: 'No estoy segura de qué sentir al respecto' },
      { time: 48, text: 'Algo en la manera en que te mueves' },
      { time: 53, text: 'Me hace sentir que no puedo vivir sin ti' },
      { time: 59, text: 'Me transporta por completo' },
      { time: 64, text: 'Quiero que te quedes' },
      { time: 72, text: 'No es mucha vida la que estás viviendo' },
      { time: 77, text: 'No es algo que solo tomas, es un regalo' },
      { time: 83, text: 'Vueltas y vueltas y vueltas damos sin parar' },
      { time: 89, text: 'Oh, dime ahora, dime ahora, dime si ya lo sabes' },
      { time: 95, text: 'No estoy seguro de qué sentir al respecto' },
      { time: 100, text: 'Algo en la forma en que te mueves' },
      { time: 106, text: 'Me hace sentir que no puedo vivir sin ti' },
      { time: 111, text: 'Me transporta por completo' },
      { time: 117, text: 'Y quiero que te quedes' },
      { time: 123, text: 'Ooh, la razón por la que resisto' },
      { time: 129, text: 'Porque necesito que este vacío se vaya' },
      { time: 135, text: 'Es curioso que tú seas el que está roto' },
      { time: 139, text: 'Pero yo era quien necesitaba ser salvada' },
      { time: 144, text: 'Porque cuando nunca ves la luz' },
      { time: 148, text: 'Es difícil saber cuál de los dos se está rindiendo' },
      { time: 153, text: 'No estoy segura de qué sentir al respecto' },
      { time: 158, text: 'Algo en la manera en que te mueves' },
      { time: 163, text: 'Me hace sentir que no puedo vivir sin ti' },
      { time: 168, text: 'Me transporta por completo' },
      { time: 173, text: 'Quiero que te quedes... quédate' },
    ],
    tl: [
      { time: 0, text: '♪ (Mahinahong intro ng piyano) ♪' },
      { time: 10, text: 'Sa simula pa lang, parang lagnat' },
      { time: 14, text: 'Malamig na pawis, pusong nananalig' },
      { time: 19, text: "Tinaas ko ang aking mga kamay, 'Ipakita mo sa akin'" },
      { time: 25, text: "Sabi niya, 'Kung kaya mo, lumapit ka pa'" },
      { time: 31, text: 'Paikot-ikot at paikot-ikot tayo kung saan' },
      { time: 37, text: 'Oh, sabihin mo ngayon, sabihin mo kung alam mo na' },
      { time: 43, text: 'Hindi ko tiyak kung ano ang mararamdaman' },
      { time: 48, text: 'May kung ano sa bawat galaw mo' },
      { time: 53, text: 'Na nagpaparamdam na di ko kayang mabuhay nang wala ka' },
      { time: 59, text: 'Dinadala ako hanggang dulo' },
      { time: 64, text: 'Gusto kong manatili ka' },
      { time: 72, text: 'Hindi ito tunay na buhay na iyong tinatahak' },
      { time: 77, text: 'Hindi lang basta kinukuha, ito ay ibinibigay' },
      { time: 83, text: 'Paikot-ikot at paikot-ikot tayo kung saan' },
      { time: 89, text: 'Oh, sabihin mo ngayon, sabihin mo kung alam mo na' },
      { time: 95, text: 'Hindi ko tiyak kung ano ang mararamdaman' },
      { time: 100, text: 'May kakaiba sa iyong paggalaw' },
      { time: 106, text: 'Pakiramdam ko hindi ko kayang mawala ka' },
      { time: 111, text: 'Dinadala ako hanggang dulo' },
      { time: 117, text: 'At gusto kong manatili ka' },
      { time: 123, text: 'Ooh, ang dahilan kung bakit kumakapit' },
      { time: 129, text: 'Dahil kailangang mapuno ang puwang na ito' },
      { time: 135, text: 'Nakapagtataka na ikaw ang wasak' },
      { time: 139, text: 'Ngunit ako ang tanging kailangang iligtas' },
      { time: 144, text: 'Dahil kapag hindi mo kailanman nakikita ang liwanag' },
      { time: 148, text: 'Mahirap malaman kung sino sa atin ang sumusuko' },
      { time: 153, text: 'Hindi ko tiyak kung ano ang mararamdaman' },
      { time: 158, text: 'May kung ano sa bawat galaw mo' },
      { time: 163, text: 'Na nagpaparamdam na di ko kayang mabuhay nang wala ka' },
      { time: 168, text: 'Dinadala ako hanggang dulo' },
      { time: 173, text: 'Gusto kong manatili ka... manatili ka' },
    ],
    ja: [
      { time: 0, text: '♪ (穏やかなピアノのイントロ) ♪' },
      { time: 10, text: 'ずっと、まるで熱病のようだった' },
      { time: 14, text: '冷や汗を流し、夢中になって信じていた' },
      { time: 19, text: '両手を上げて「何か見せて」と言った' },
      { time: 25, text: '彼は「勇気があるなら、もっと近くにおいで」と答えた' },
      { time: 31, text: 'ぐるぐると、私たちは回り続ける' },
      { time: 37, text: 'ねえ、今教えて、分かっているなら言ってよ' },
      { time: 43, text: 'どう受け止めればいいのか分からない' },
      { time: 48, text: 'あなたの仕草のひとつひとつが' },
      { time: 53, text: 'あなたなしでは生きられないと思わせる' },
      { time: 59, text: '私をどこまでも連れていく' },
      { time: 64, text: 'そばにいてほしい' },
      { time: 72, text: 'それは生きているとは言えない人生だよ' },
      { time: 77, text: 'ただ奪うものじゃない、与えられるものなんだ' },
      { time: 83, text: 'ぐるぐると、私たちは回り続ける' },
      { time: 89, text: 'ねえ、今教えて、分かっているなら言ってよ' },
      { time: 95, text: 'どんな気持ちでいればいいか分からない' },
      { time: 100, text: 'あなたのその仕草が' },
      { time: 106, text: 'あなたなしでは生きられないと思わせる' },
      { time: 111, text: 'すべてを連れ去っていく' },
      { time: 117, text: 'そして、そばにいてほしいんだ' },
      { time: 123, text: 'ああ、私がすがりつく理由' },
      { time: 129, text: 'この心の穴を埋めたいから' },
      { time: 135, text: '傷ついているのはあなたなのに' },
      { time: 139, text: '救われるべきだったのは私だけだった' },
      { time: 144, text: '光を見失っているとき' },
      { time: 148, text: 'どちらが崩れ落ちているのか見分けがつかない' },
      { time: 153, text: 'どう受け止めればいいのか分からない' },
      { time: 158, text: 'あなたのその身のこなしが' },
      { time: 163, text: 'あなたなしでは生きられないと思わせる' },
      { time: 168, text: '私をどこまでも連れていく' },
      { time: 173, text: 'お願い、そばにいて…ここにいて' },
    ],
    fr: [
      { time: 0, text: '♪ (Douce intro au piano) ♪' },
      { time: 10, text: "Depuis le début, c'était une fièvre" },
      { time: 14, text: 'Une sueur froide, une croyante passionnée' },
      { time: 19, text: "J'ai levé les bras au ciel, en disant 'Montre-moi quelque chose'" },
      { time: 25, text: "Il a dit, 'Si tu l'oses, approche-toi un peu plus'" },
      { time: 31, text: 'Encore et encore, nous tournons en rond' },
      { time: 37, text: 'Oh, dis-le-moi maintenant, dis-moi que tu sais' },
      { time: 43, text: 'Pas vraiment sûre de ce que je ressens' },
      { time: 48, text: 'Quelque chose dans ta façon de bouger' },
      { time: 53, text: 'Me fait sentir que je ne peux vivre sans toi' },
      { time: 59, text: "Ça m'emporte tout entier" },
      { time: 64, text: 'Je veux que tu restes' },
      { time: 72, text: "Ce n'est pas vraiment une vie que tu mènes" },
      { time: 77, text: "Ce n'est pas juste quelque chose qu'on prend, c'est offert" },
      { time: 83, text: 'Encore et encore, nous tournons en rond' },
      { time: 89, text: 'Oh, dis-le-moi maintenant, dis-moi que tu sais' },
      { time: 95, text: 'Pas vraiment sûr de ce que je ressens' },
      { time: 100, text: 'Quelque chose dans ta façon de bouger' },
      { time: 106, text: 'Me fait sentir que je ne peux pas vivre sans toi' },
      { time: 111, text: "Ça m'emporte tout entier" },
      { time: 117, text: 'Et je veux que tu restes' },
      { time: 123, text: 'Ooh, la raison pour laquelle je m’accroche' },
      { time: 129, text: "C'est que j'ai besoin de combler ce vide" },
      { time: 135, text: "C'est drôle, tu es celui qui est brisé" },
      { time: 139, text: "Mais j'étais la seule à devoir être sauvée" },
      { time: 144, text: "Parce que quand on ne voit jamais la lumière" },
      { time: 148, text: "C'est dur de savoir lequel de nous s'effondre" },
      { time: 153, text: 'Pas vraiment sûre de ce que je ressens' },
      { time: 158, text: 'Quelque chose dans ta manière d’être' },
      { time: 163, text: 'Me fait sentir que je ne peux vivre sans toi' },
      { time: 168, text: "Ça m'emporte tout entier" },
      { time: 173, text: 'Je veux que tu restes... reste' },
    ],
    de: [
      { time: 0, text: '♪ (Sanftes Klavier-Intro) ♪' },
      { time: 10, text: 'Die ganze Zeit war es wie ein Fieber' },
      { time: 14, text: 'Kalter Schweiß, ein heißblütiger Glaube' },
      { time: 19, text: 'Ich warf die Hände in die Luft und sagte: Zeig mir was' },
      { time: 25, text: 'Er sagte: Wenn du dich traust, komm etwas näher' },
      { time: 31, text: 'Rundherum und immer weiter im Kreis' },
      { time: 37, text: 'Oh, sag es mir jetzt, sag mir, dass du es weißt' },
      { time: 43, text: 'Ich weiß nicht genau, was ich fühlen soll' },
      { time: 48, text: 'Etwas an der Art, wie du dich bewegst' },
      { time: 53, text: 'Lässt mich glauben, dass ich ohne dich nicht leben kann' },
      { time: 59, text: 'Es nimmt mich ganz gefangen' },
      { time: 64, text: 'Ich will, dass du bleibst' },
      { time: 72, text: 'Das ist kaum ein Leben, das du führst' },
      { time: 77, text: 'Es ist nichts, was man einfach nimmt, es wird geschenkt' },
      { time: 83, text: 'Rundherum und immer weiter im Kreis' },
      { time: 89, text: 'Oh, sag es mir jetzt, sag mir, dass du es weißt' },
      { time: 95, text: 'Nicht wirklich sicher, wie ich fühlen soll' },
      { time: 100, text: 'Etwas an der Art, wie du dich bewegst' },
      { time: 106, text: 'Lässt mich spüren, dass ich ohne dich nicht sein kann' },
      { time: 111, text: 'Es trägt mich ganz davon' },
      { time: 117, text: 'Und ich will, dass du bleibst' },
      { time: 123, text: 'Ooh, der Grund, warum ich festhalte' },
      { time: 129, text: 'Weil diese Leere verschwinden muss' },
      { time: 135, text: 'Komisch, dass du der Zerbrochene bist' },
      { time: 139, text: 'Aber ich die Einzige war, die Rettung brauchte' },
      { time: 144, text: 'Denn wenn man das Licht nie sieht' },
      { time: 148, text: 'Ist es schwer zu wissen, wer von uns nachgibt' },
      { time: 153, text: 'Nicht wirklich sicher, was ich fühlen soll' },
      { time: 158, text: 'Etwas an der Art, wie du dich bewegst' },
      { time: 163, text: 'Gibt mir das Gefühl, nicht ohne dich leben zu können' },
      { time: 168, text: 'Es nimmt mich ganz ein' },
      { time: 173, text: 'Ich will, dass du bleibst... bleib' },
    ],
    ko: [
      { time: 0, text: '♪ (부드러운 피아노 도입부) ♪' },
      { time: 10, text: '처음부터, 그건 마치 열병 같았어' },
      { time: 14, text: '식은땀을 흘리며 열정적으로 믿었지' },
      { time: 19, text: "두 손을 하늘로 들며 말했어, '뭐든 보여줘 봐'" },
      { time: 25, text: "그는 말했지, '자신 있다면, 조금 더 가까이 와'" },
      { time: 31, text: '빙글빙글 우리는 맴돌고 있어' },
      { time: 37, text: '오, 지금 내게 말해줘, 너도 알고 있다고' },
      { time: 43, text: '어떤 마음이어야 할지 잘 모르겠어' },
      { time: 48, text: '너의 움직임 속 그 무언가가' },
      { time: 53, text: '너 없이는 살 수 없을 것만 같게 해' },
      { time: 59, text: '나를 온전히 사로잡아' },
      { time: 64, text: '네가 곁에 머물렀으면 좋겠어' },
      { time: 72, text: '네가 사는 건 그리 온전한 삶이 아니야' },
      { time: 77, text: '그냥 쥐는 게 아니라, 서로 주는 선물이지' },
      { time: 83, text: '빙글빙글 우리는 맴돌고 있어' },
      { time: 89, text: '오, 지금 말해줘, 이제는 알고 있다고' },
      { time: 95, text: '어떻게 느껴야 할지 잘 모르겠어' },
      { time: 100, text: '너의 움직임 속 그 어떤 것이' },
      { time: 106, text: '너 없이 살 수 없을 것 같은 기분을 만들어' },
      { time: 111, text: '나를 온전히 이끌어가' },
      { time: 117, text: '그리고 난 네가 머물러 주길 바라' },
      { time: 123, text: '오, 내가 붙잡고 있는 이유' },
      { time: 129, text: '이 빈자리가 채워지길 원하기에' },
      { time: 135, text: '상처 입은 건 너인데' },
      { time: 139, text: '정작 구원이 필요했던 건 나뿐이었어' },
      { time: 144, text: '빛을 전혀 보지 못할 때는' },
      { time: 148, text: '우리 중 누가 무너지고 있는지 알기 어렵잖아' },
      { time: 153, text: '어떤 마음이어야 할지 여전히 모르겠어' },
      { time: 158, text: '너의 그 몸짓 하나하나가' },
      { time: 163, text: '너 없이는 살 수 없을 것처럼 느껴지게 해' },
      { time: 168, text: '나를 전부 데려가' },
      { time: 173, text: '네가 머물렀으면 해... 머물러줘' },
    ],
  },

  // 2. Send My Love (To Your New Lover) - Adele
  'song-1788808460743': {
    en: [
      { time: 0, text: '♪ (Acoustic guitar strum intro) ♪' },
      { time: 6, text: 'Just the guitar, okay, cool' },
      { time: 10, text: 'This was all you, none of it me' },
      { time: 14, text: 'You put your hands all over my body and told me, mmm' },
      { time: 19, text: 'You told me you were ready' },
      { time: 23, text: 'For the big one, for the big jump' },
      { time: 28, text: "I'd be your last love, everlasting, you and me, mmm" },
      { time: 33, text: 'That was what you told me' },
      { time: 37, text: "I'm giving you up, I've forgiven it all" },
      { time: 43, text: 'You set me free' },
      { time: 47, text: 'Send my love to your new lover' },
      { time: 51, text: 'Treat her better' },
      { time: 55, text: "We've gotta let go of all of our ghosts" },
      { time: 59, text: "We both know we ain't kids no more" },
      { time: 64, text: 'Send my love to your new lover' },
      { time: 68, text: 'Treat her better' },
      { time: 72, text: "We've gotta let go of all of our ghosts" },
      { time: 76, text: "We both know we ain't kids no more" },
      { time: 81, text: 'I was too strong, you were trembling' },
      { time: 85, text: "You couldn't handle the hot heat rising" },
      { time: 90, text: "Baby, I'm still rising" },
      { time: 94, text: 'I was running, you were walking' },
      { time: 98, text: 'You couldn\'t keep up, you were falling down' },
      { time: 103, text: "There's only one way down" },
      { time: 107, text: "I'm giving you up, I've forgiven it all" },
      { time: 113, text: 'You set me free, oh' },
      { time: 117, text: 'Send my love to your new lover' },
      { time: 121, text: 'Treat her better' },
      { time: 125, text: "We've gotta let go of all of our ghosts" },
      { time: 129, text: "We both know we ain't kids no more" },
      { time: 134, text: "If you're ready, if you're ready" },
      { time: 139, text: "If you're ready, I am ready" },
      { time: 143, text: "We both know we ain't kids no more" },
      { time: 148, text: 'Send my love to your new lover' },
      { time: 152, text: 'Treat her better' },
      { time: 156, text: "We've gotta let go of all of our ghosts" },
      { time: 160, text: "We both know we ain't kids no more" },
      { time: 165, text: 'Treat her better, treat her better...' },
      { time: 172, text: "We ain't kids no more" },
    ],
    es: [
      { time: 0, text: '♪ (Intro con rasgueo de guitarra acústica) ♪' },
      { time: 6, text: 'Solo la guitarra, está bien, genial' },
      { time: 10, text: 'Todo esto fuiste tú, nada de mí' },
      { time: 14, text: 'Pusiste tus manos en todo mi cuerpo y me dijiste, mmm' },
      { time: 19, text: 'Me dijiste que estabas listo' },
      { time: 23, text: 'Para el gran paso, para el gran salto' },
      { time: 28, text: 'Que sería tu último amor, eterno, tú y yo, mmm' },
      { time: 33, text: 'Eso fue lo que me dijiste' },
      { time: 37, text: 'Te estoy dejando ir, lo he perdonado todo' },
      { time: 43, text: 'Me has hecho libre' },
      { time: 47, text: 'Mándale mi amor a tu nuevo amor' },
      { time: 51, text: 'Trátala mejor' },
      { time: 55, text: 'Tenemos que dejar ir a todos nuestros fantasmas' },
      { time: 59, text: 'Los dos sabemos que ya no somos niños' },
      { time: 64, text: 'Mándale mi amor a tu nuevo amor' },
      { time: 68, text: 'Trátala mejor' },
      { time: 72, text: 'Tenemos que dejar ir a todos nuestros fantasmas' },
      { time: 76, text: 'Los dos sabemos que ya no somos niños' },
      { time: 81, text: 'Fui demasiado fuerte, tú estabas temblando' },
      { time: 85, text: 'No pudiste soportar el calor en aumento' },
      { time: 90, text: 'Cariño, todavía sigo en ascenso' },
      { time: 94, text: 'Yo corría, tú caminabas' },
      { time: 98, text: 'No pudiste seguirme el paso, te estabas cayendo' },
      { time: 103, text: 'Solo hay un camino hacia abajo' },
      { time: 107, text: 'Te estoy dejando ir, lo he perdonado todo' },
      { time: 113, text: 'Me has dejado libre, oh' },
      { time: 117, text: 'Mándale mi amor a tu nuevo amor' },
      { time: 121, text: 'Trátala mejor' },
      { time: 125, text: 'Tenemos que dejar ir a todos nuestros fantasmas' },
      { time: 129, text: 'Los dos sabemos que ya no somos niños' },
      { time: 134, text: 'Si estás listo, si estás listo' },
      { time: 139, text: 'Si estás listo, yo estoy lista' },
      { time: 143, text: 'Los dos sabemos que ya no somos niños' },
      { time: 148, text: 'Mándale mi amor a tu nuevo amor' },
      { time: 152, text: 'Trátala mejor' },
      { time: 156, text: 'Tenemos que dejar ir a todos nuestros fantasmas' },
      { time: 160, text: 'Los dos sabemos que ya no somos niños' },
      { time: 165, text: 'Trátala mejor, trátala mejor...' },
      { time: 172, text: 'Ya no somos niños' },
    ],
    tl: [
      { time: 0, text: '♪ (Intro ng akustikong gitara) ♪' },
      { time: 6, text: 'Gitara lang, sige ayos' },
      { time: 10, text: 'Lahat ng ito ay ikaw, walang bahagi sa akin' },
      { time: 14, text: 'Hinawakan mo ako at sinabing, mmm' },
      { time: 19, text: 'Sinabi mong handa ka na' },
      { time: 23, text: 'Para sa malaking hakbang, para sa pagtalon' },
      { time: 28, text: 'Ako ang huli mong pag-ibig, walang hanggan' },
      { time: 33, text: 'Iyon ang sinabi mo sa akin' },
      { time: 37, text: 'Binitiwan na kita, pinatawad ko na ang lahat' },
      { time: 43, text: 'Pinalaya mo ako' },
      { time: 47, text: 'Ihatid mo ang pagbati sa bago mong minamahal' },
      { time: 51, text: 'Tratuhin mo siya nang mas mabuti' },
      { time: 55, text: 'Kailangan na nating pakawalan ang mga alaala' },
      { time: 59, text: 'Pareho nating alam na hindi na tayo bata' },
      { time: 64, text: 'Ihatid mo ang pagbati sa bago mong minamahal' },
      { time: 68, text: 'Tratuhin mo siya nang mas mabuti' },
      { time: 72, text: 'Kailangan na nating pakawalan ang mga alaala' },
      { time: 76, text: 'Pareho nating alam na hindi na tayo bata' },
      { time: 81, text: 'Masyado akong matatag, ikaw ay nangangatal' },
      { time: 85, text: 'Hindi mo nakayanan ang tumitinding init' },
      { time: 90, text: 'Mahal, pataas pa rin ako' },
      { time: 94, text: 'Ako ay tumatakbo, ikaw ay naglalakad' },
      { time: 98, text: 'Hindi ka nakahabol, ikaw ay bumagsak' },
      { time: 103, text: 'Iisa lang ang daan pababa' },
      { time: 107, text: 'Binitiwan na kita, pinatawad ko na ang lahat' },
      { time: 113, text: 'Pinalaya mo ako, oh' },
      { time: 117, text: 'Ihatid mo ang pagbati sa bago mong minamahal' },
      { time: 121, text: 'Tratuhin mo siya nang mas mabuti' },
      { time: 125, text: 'Kailangan na nating pakawalan ang mga alaala' },
      { time: 129, text: 'Pareho nating alam na hindi na tayo bata' },
      { time: 134, text: 'Kung handa ka na, kung handa ka na' },
      { time: 139, text: 'Kung handa ka na, handa na rin ako' },
      { time: 143, text: 'Alam nating dalawa na di na tayo bata' },
      { time: 148, text: 'Ihatid mo ang pagbati sa bago mong minamahal' },
      { time: 152, text: 'Tratuhin mo siya nang mas mabuti' },
      { time: 156, text: 'Pakawalan na natin ang nakaraan' },
      { time: 160, text: 'Alam nating dalawa na hindi na tayo bata' },
      { time: 165, text: 'Tratuhin mo siya nang maayos...' },
      { time: 172, text: 'Hindi na tayo bata' },
    ],
    ja: [
      { time: 0, text: '♪ (アコースティックギターのイントロ) ♪' },
      { time: 6, text: 'ギターだけでいい、そう、いいね' },
      { time: 10, text: '全部あなたのせい、私じゃない' },
      { time: 14, text: '私に触れて、囁いたよね' },
      { time: 19, text: '覚悟はできているって' },
      { time: 23, text: '大きな一歩、大きな跳躍への覚悟が' },
      { time: 28, text: '私があなたの最後の愛、永遠にふたりで' },
      { time: 33, text: 'そう言ってくれたじゃない' },
      { time: 37, text: 'もうあなたを手放すわ、すべて許したの' },
      { time: 43, text: 'あなたが私を自由にしてくれた' },
      { time: 47, text: '新しい恋人に愛を伝えてあげて' },
      { time: 51, text: 'もっと大切にしてあげてね' },
      { time: 55, text: '過去の亡霊たちを手放さなきゃ' },
      { time: 59, text: 'もう私たち、子供じゃないんだから' },
      { time: 64, text: '新しい恋人に愛を伝えて' },
      { time: 68, text: 'もっと優しくしてあげて' },
      { time: 72, text: '過去の亡霊たちを手放さなきゃ' },
      { time: 76, text: 'もう私たちは子供じゃない' },
      { time: 81, text: '私は強すぎた、あなたは震えていた' },
      { time: 85, text: '立ちのぼる熱気に耐えられなかったのね' },
      { time: 90, text: 'ベイビー、私はまだ昇り続けている' },
      { time: 94, text: '私は走っていた、あなたは歩いていた' },
      { time: 98, text: '追いつけずに、あなたは崩れ落ちていった' },
      { time: 103, text: '落ちていく道はひとつだけ' },
      { time: 107, text: 'もう諦めるわ、すべてを許したの' },
      { time: 113, text: 'あなたが私を自由にしたのよ' },
      { time: 117, text: '新しい恋人に愛を届けて' },
      { time: 121, text: '彼女をもっと大切にしてあげて' },
      { time: 125, text: 'すべての過去の亡霊を解放しよう' },
      { time: 129, text: 'もう子供じゃないって分かってるでしょ' },
      { time: 134, text: '準備ができてるなら' },
      { time: 139, text: 'あなたが良ければ、私も覚悟はできてる' },
      { time: 143, text: 'もう子供じゃないんだから' },
      { time: 148, text: '新しい恋人によろしく伝えて' },
      { time: 152, text: 'もっと大切にしてあげてね' },
      { time: 156, text: '過去のしがらみはすべて捨てよう' },
      { time: 160, text: '私たち、もう子供じゃない' },
      { time: 165, text: 'もっと大切に…大切にしてあげて' },
      { time: 172, text: 'もう子供じゃないんだから' },
    ],
    fr: [
      { time: 0, text: '♪ (Intro guitare acoustique) ♪' },
      { time: 6, text: 'Juste la guitare, d’accord, super' },
      { time: 10, text: "C'était entièrement toi, rien de moi" },
      { time: 14, text: "Tu as posé tes mains sur moi et m'as dit, mmm" },
      { time: 19, text: 'Tu disais que tu étais prêt' },
      { time: 23, text: 'Pour le grand saut, pour la grande aventure' },
      { time: 28, text: 'Que je serais ton dernier amour éternel, toi et moi' },
      { time: 33, text: "C'est ce que tu m'avais promis" },
      { time: 37, text: "Je te laisse partir, j'ai tout pardonné" },
      { time: 43, text: "Tu m'as libérée" },
      { time: 47, text: 'Transmets mon amour à ta nouvelle conquête' },
      { time: 51, text: 'Traite-la mieux' },
      { time: 55, text: 'Il faut lâcher prise de tous nos fantômes' },
      { time: 59, text: 'On sait tous les deux qu’on n’est plus des enfants' },
      { time: 64, text: 'Transmets mon amour à ta nouvelle amoureuse' },
      { time: 68, text: 'Sois meilleur avec elle' },
      { time: 72, text: 'Laissons partir tous nos fantômes' },
      { time: 76, text: 'On sait tous les deux qu’on n’est plus des gosses' },
      { time: 81, text: "J'étais trop forte, tu tremblais" },
      { time: 85, text: 'Tu ne pouvais pas supporter cette ardeur montante' },
      { time: 90, text: "Chéri, je m'élève toujours" },
      { time: 94, text: 'Je courais, tu marchais' },
      { time: 98, text: 'Tu ne pouvais pas suivre, tu tombais' },
      { time: 103, text: "Il n'y a qu'une seule issue vers le bas" },
      { time: 107, text: "Je t'abandonne, j'ai tout pardonné" },
      { time: 113, text: "Tu m'as rendue libre, oh" },
      { time: 117, text: 'Transmets mon amour à ta nouvelle amante' },
      { time: 121, text: 'Prends bien soin d’elle' },
      { time: 125, text: 'Oublions tous nos fantômes passés' },
      { time: 129, text: "On sait bien qu'on n'est plus des enfants" },
      { time: 134, text: 'Si tu es prêt, si tu es prêt' },
      { time: 139, text: 'Si tu es prêt, je suis prête' },
      { time: 143, text: 'Nous ne sommes plus des enfants' },
      { time: 148, text: 'Donne mon amour à ta nouvelle amoureuse' },
      { time: 152, text: 'Traite-la mieux' },
      { time: 156, text: 'Délivrons-nous de nos fantômes' },
      { time: 160, text: 'Nous ne sommes plus des gosses' },
      { time: 165, text: 'Traite-la mieux, sois bon avec elle...' },
      { time: 172, text: 'Nous ne sommes plus des enfants' },
    ],
    de: [
      { time: 0, text: '♪ (Akustikgitarren-Intro) ♪' },
      { time: 6, text: 'Nur die Gitarre, okay, cool' },
      { time: 10, text: 'Das lag alles an dir, nichts an mir' },
      { time: 14, text: 'Du hast mich berührt und mir gesagt, mmm' },
      { time: 19, text: 'Du hast gesagt, du wärst bereit' },
      { time: 23, text: 'Für den großen Sprung, das große Ganze' },
      { time: 28, text: 'Dass ich deine letzte, ewige Liebe sein würde' },
      { time: 33, text: 'Das hast du mir versprochen' },
      { time: 37, text: 'Ich gebe dich auf, ich habe alles vergeben' },
      { time: 43, text: 'Du hast mich befreit' },
      { time: 47, text: 'Grüß deine neue Liebe von mir' },
      { time: 51, text: 'Behandle sie besser' },
      { time: 55, text: 'Wir müssen all unsere Geister loslassen' },
      { time: 59, text: 'Wir wissen beide, dass wir keine Kinder mehr sind' },
      { time: 64, text: 'Schick meine Liebe an deine Neue' },
      { time: 68, text: 'Behandle sie besser' },
      { time: 72, text: 'Wir müssen die Geister der Vergangenheit loslassen' },
      { time: 76, text: 'Wir sind keine Kinder mehr' },
      { time: 81, text: 'Ich war zu stark, du hast gezittert' },
      { time: 85, text: 'Du konntest die steigende Hitze nicht ertragen' },
      { time: 90, text: 'Baby, ich steige immer noch auf' },
      { time: 94, text: 'Ich rannte, du gingst nur' },
      { time: 98, text: 'Du konntest nicht mithalten und stürztest ab' },
      { time: 103, text: 'Es gibt nur einen Weg nach unten' },
      { time: 107, text: 'Ich gebe dich auf, ich habe alles verziehen' },
      { time: 113, text: 'Du hast mich befreit, oh' },
      { time: 117, text: 'Grüß deine neue Liebe von mir' },
      { time: 121, text: 'Sei besser zu ihr' },
      { time: 125, text: 'Lassen wir all unsere Geister ziehen' },
      { time: 129, text: 'Wir sind keine Kinder mehr' },
      { time: 134, text: 'Wenn du bereit bist' },
      { time: 139, text: 'Wenn du bereit bist, bin ich es auch' },
      { time: 143, text: 'Wir wissen, dass wir erwachsen sind' },
      { time: 148, text: 'Grüß deine neue Liebe' },
      { time: 152, text: 'Behandle sie besser' },
      { time: 156, text: 'Lassen wir unsere Geister los' },
      { time: 160, text: 'Wir sind keine Kinder mehr' },
      { time: 165, text: 'Behandle sie besser, sei gut zu ihr...' },
      { time: 172, text: 'Wir sind keine Kinder mehr' },
    ],
    ko: [
      { time: 0, text: '♪ (어쿠스틱 기타 인트로) ♪' },
      { time: 6, text: '기타만 연주해 줘, 좋아, 멋져' },
      { time: 10, text: '전부 네 탓이었어, 내 탓은 전혀 없어' },
      { time: 14, text: '날 감싸 안으며 내게 속삭였지, mmm' },
      { time: 19, text: '준비가 되었다고 말했잖아' },
      { time: 23, text: '그 큰 도약을 향해 뛰어들 준비가' },
      { time: 28, text: '내가 너의 마지막 영원한 사랑이 될 거라고' },
      { time: 33, text: '그게 네가 내게 했던 말이었어' },
      { time: 37, text: '이제 널 보내줄게, 모든 걸 용서했어' },
      { time: 43, text: '날 자유롭게 해줬어' },
      { time: 47, text: '너의 새 연인에게 내 사랑을 전해줘' },
      { time: 51, text: '그녀에겐 더 잘해줘' },
      { time: 55, text: '우린 모든 과거의 유령들을 털어내야 해' },
      { time: 59, text: '우린 둘 다 이제 어린애가 아니잖아' },
      { time: 64, text: '새 연인에게 내 안부를 전해줘' },
      { time: 68, text: '더 잘 대해주길 바라' },
      { time: 72, text: '우리의 과거는 이제 놓아주자' },
      { time: 76, text: '우리 둘 다 이제 다 자랐잖아' },
      { time: 81, text: '난 너무 강했고, 넌 떨고 있었지' },
      { time: 85, text: '점점 뜨거워지는 열기를 넌 감당하지 못했어' },
      { time: 90, text: '그대여, 난 여전히 날아오르는 중이야' },
      { time: 94, text: '난 달렸고, 넌 걷고 있었어' },
      { time: 98, text: '따라오지 못해 넌 주저앉고 말았지' },
      { time: 103, text: '추락할 길은 하나뿐이었어' },
      { time: 107, text: '널 놓아줄게, 전부 용서했어' },
      { time: 113, text: '날 자유롭게 놓아줘서 고마워' },
      { time: 117, text: '새 연인에게 내 인사를 전해줘' },
      { time: 121, text: '그녀는 더 아껴줘' },
      { time: 125, text: '우리의 모든 미련을 털어내자' },
      { time: 129, text: '우린 더 이상 아이가 아니잖아' },
      { time: 134, text: '네가 준비되었다면' },
      { time: 139, text: '네가 준비됐다면 나도 준비됐어' },
      { time: 143, text: '우린 이제 어린애가 아니야' },
      { time: 148, text: '너의 새로운 사랑에게 전해줘' },
      { time: 152, text: '더 잘해주라고' },
      { time: 156, text: '과거의 그림자는 묻어두자' },
      { time: 160, text: '우린 이제 아이가 아니니까' },
      { time: 165, text: '더 잘해줘, 아껴줘...' },
      { time: 172, text: '우린 이제 다 컸어' },
    ],
  },

  // 3. Dancing With Your Ghost - Sasha Alex Sloan
  'song-1788806751595': {
    en: [
      { time: 0, text: '♪ (Melancholy acoustic intro) ♪' },
      { time: 8, text: 'Yelling at the sky' },
      { time: 12, text: 'Screaming at the world' },
      { time: 17, text: "Baby, why'd you go away?" },
      { time: 21, text: "I'm still your girl" },
      { time: 25, text: 'Holding on too tight' },
      { time: 30, text: 'Head up in the clouds' },
      { time: 34, text: 'Heaven only knows where you are now' },
      { time: 42, text: 'How do I love, how do I love again?' },
      { time: 50, text: 'How do I trust, how do I trust again?' },
      { time: 59, text: "I stay up all night, tell myself I'm alright" },
      { time: 67, text: "Baby, you're just harder to see than most" },
      { time: 75, text: "I put the record on, wait 'til I hear our song" },
      { time: 84, text: "Every night, I'm dancing with your ghost" },
      { time: 92, text: "Every night, I'm dancing with your ghost" },
      { time: 101, text: 'Never got the chance' },
      { time: 105, text: 'To say a last goodbye' },
      { time: 110, text: 'I gotta move on' },
      { time: 114, text: 'But it hurts to try' },
      { time: 122, text: 'How do I love, how do I love again?' },
      { time: 131, text: 'How do I trust, how do I trust again?' },
      { time: 139, text: "I stay up all night, tell myself I'm alright" },
      { time: 148, text: "Baby, you're just harder to see than most" },
      { time: 156, text: "I put the record on, wait 'til I hear our song" },
      { time: 165, text: "Every night, I'm dancing with your ghost" },
      { time: 173, text: "Every night, I'm dancing with your ghost" },
    ],
    es: [
      { time: 0, text: '♪ (Intro acústico melancólico) ♪' },
      { time: 8, text: 'Gritándole al cielo' },
      { time: 12, text: 'Gritándole al mundo' },
      { time: 17, text: 'Cariño, ¿por qué te fuiste?' },
      { time: 21, text: 'Todavía sigo siendo tu chica' },
      { time: 25, text: 'Aferrándome con demasiada fuerza' },
      { time: 30, text: 'Con la cabeza en las nubes' },
      { time: 34, text: 'Solo el cielo sabe dónde estás ahora' },
      { time: 42, text: '¿Cómo vuelvo a amar? ¿Cómo amo otra vez?' },
      { time: 50, text: '¿Cómo vuelvo a confiar? ¿Cómo confío otra vez?' },
      { time: 59, text: 'Me quedo despierta toda la noche, diciéndome que estoy bien' },
      { time: 67, text: 'Cariño, solo eres más difícil de ver que los demás' },
      { time: 75, text: 'Pongo el disco y espero hasta escuchar nuestra canción' },
      { time: 84, text: 'Cada noche, bailo con tu fantasma' },
      { time: 92, text: 'Cada noche, bailo con tu fantasma' },
      { time: 101, text: 'Nunca tuve la oportunidad' },
      { time: 105, text: 'De decir un último adiós' },
      { time: 110, text: 'Tengo que seguir adelante' },
      { time: 114, text: 'Pero duele tanto intentarlo' },
      { time: 122, text: '¿Cómo vuelvo a amar? ¿Cómo amo otra vez?' },
      { time: 131, text: '¿Cómo vuelvo a confiar? ¿Cómo confío otra vez?' },
      { time: 139, text: 'Me quedo despierta toda la noche, diciéndome que estoy bien' },
      { time: 148, text: 'Cariño, solo eres más difícil de ver que los demás' },
      { time: 156, text: 'Pongo el disco y espero hasta escuchar nuestra canción' },
      { time: 165, text: 'Cada noche, bailo con tu fantasma' },
      { time: 173, text: 'Cada noche, bailo con tu fantasma' },
    ],
    tl: [
      { time: 0, text: '♪ (Malungkot na akustikong intro) ♪' },
      { time: 8, text: 'Sumisigaw sa kalangitan' },
      { time: 12, text: 'Humihiyaw sa mundo' },
      { time: 17, text: 'Giliw, bakit ka lumayo?' },
      { time: 21, text: 'Ako pa rin ang iyong giliw' },
      { time: 25, text: 'Humahawak nang labis na mahigpit' },
      { time: 30, text: 'Ulo ay nasa alapaap' },
      { time: 34, text: 'Langit lamang ang may alam kung nasaan ka ngayon' },
      { time: 42, text: 'Paano ako magmamahal, paano iibig muli?' },
      { time: 50, text: 'Paano magtitiwala, paano magtitiwala muli?' },
      { time: 59, text: 'Gising ako magdamag, sinasabi sa sarili na ayos lang' },
      { time: 67, text: 'Mahal, mas mahirap ka lang makita kaysa sa iba' },
      { time: 75, text: 'Pinapatugtog ko ang plaka, naghihintay sa ating awit' },
      { time: 84, text: 'Gabi-gabi, sumasayaw ako kasama ng iyong multo' },
      { time: 92, text: 'Gabi-gabi, sumasayaw ako kasama ng iyong multo' },
      { time: 101, text: 'Hindi man lang nagkaroon ng pagkakataon' },
      { time: 105, text: 'Upang magpaalam sa huling sandali' },
      { time: 110, text: 'Kailangan ko nang magpatuloy' },
      { time: 114, text: 'Ngunit masakit sumubok' },
      { time: 122, text: 'Paano ako magmamahal muli?' },
      { time: 131, text: 'Paano ako magtitiwala muli?' },
      { time: 139, text: 'Gising ako magdamag, sinasabi sa sarili na ayos lang' },
      { time: 148, text: 'Mahal, mas mahirap ka lang makita kaysa sa karamihan' },
      { time: 156, text: 'Pinapatugtog ko ang plaka, naghihintay sa ating awit' },
      { time: 165, text: 'Gabi-gabi, kasayaw ko ang iyong multo' },
      { time: 173, text: 'Gabi-gabi, kasayaw ko ang iyong multo' },
    ],
    ja: [
      { time: 0, text: '♪ (切ないアコースティックの調べ) ♪' },
      { time: 8, text: '空に向かって叫んでいる' },
      { time: 12, text: '世界に向かって叫んでいる' },
      { time: 17, text: 'ねえ、どうして行ってしまったの？' },
      { time: 21, text: '私は今でもあなたの恋人なのに' },
      { time: 25, text: '強く握りしめすぎているの' },
      { time: 30, text: '心は雲の上をさまよったまま' },
      { time: 34, text: 'あなたが今どこにいるのか、神様しか知らない' },
      { time: 42, text: 'どうやって、もう一度人を愛せばいいの？' },
      { time: 50, text: 'どうやって、もう一度信じればいいの？' },
      { time: 59, text: '一晩中起きて、大丈夫だと自分に言い聞かせる' },
      { time: 67, text: 'あなたはただ、他の誰よりも見えにくいだけ' },
      { time: 75, text: 'レコードに針を落とし、ふたりの曲が流れるのを待つ' },
      { time: 84, text: '毎晩、私はあなたの幻と踊っている' },
      { time: 92, text: '毎晩、私はあなたの幻と踊っている' },
      { time: 101, text: '最後のさよならを言う' },
      { time: 105, text: 'チャンスさえ与えられなかった' },
      { time: 110, text: '前を向かなきゃいけないのに' },
      { time: 114, text: '前に進もうとするだけで胸が痛む' },
      { time: 122, text: 'どうやってまた人を愛せばいいの？' },
      { time: 131, text: 'どうやってまた信じればいいの？' },
      { time: 139, text: '夜通し起きて、平気だと自分に言い聞かせる' },
      { time: 148, text: 'あなたはただ、姿が見えないだけなんだって' },
      { time: 156, text: 'レコードをかけて、私たちの歌を待つ' },
      { time: 165, text: '毎晩、私はあなたの面影と踊っている' },
      { time: 173, text: '毎晩、あなたの幻と踊り続けるの' },
    ],
    fr: [
      { time: 0, text: '♪ (Intro mélancolique à la guitare) ♪' },
      { time: 8, text: 'Je hurle vers le ciel' },
      { time: 12, text: 'Je crie contre le monde entier' },
      { time: 17, text: "Bébé, pourquoi es-tu parti ?" },
      { time: 21, text: 'Je suis toujours ta fille' },
      { time: 25, text: 'Je m’accroche trop fort' },
      { time: 30, text: 'La tête perdue dans les nuages' },
      { time: 34, text: 'Le ciel seul sait où tu te trouves à présent' },
      { time: 42, text: 'Comment aimer, comment aimer à nouveau ?' },
      { time: 50, text: 'Comment faire confiance, comment croire à nouveau ?' },
      { time: 59, text: 'Je veille toute la nuit, me disant que tout va bien' },
      { time: 67, text: 'Bébé, tu es juste plus difficile à apercevoir que les autres' },
      { time: 75, text: 'Je lance le disque, attendant notre chanson' },
      { time: 84, text: 'Chaque nuit, je danse avec ton fantôme' },
      { time: 92, text: 'Chaque nuit, je danse avec ton fantôme' },
      { time: 101, text: "Je n'ai jamais eu la chance" },
      { time: 105, text: "De te dire un dernier adieu" },
      { time: 110, text: "Je dois aller de l'avant" },
      { time: 114, text: "Mais essayer fait trop mal" },
      { time: 122, text: 'Comment aimer à nouveau ?' },
      { time: 131, text: 'Comment accorder ma confiance à nouveau ?' },
      { time: 139, text: 'Je reste éveillée toute la nuit, me répétant que ça va' },
      { time: 148, text: 'Tu es juste plus invisible que le reste du monde' },
      { time: 156, text: 'Je mets le vinyle, j’attends notre chanson' },
      { time: 165, text: 'Toutes les nuits, je danse avec ton fantôme' },
      { time: 173, text: 'Toutes les nuits, je danse avec ton fantôme' },
    ],
    de: [
      { time: 0, text: '♪ (Melancholisches Akustik-Intro) ♪' },
      { time: 8, text: 'Ich schreie den Himmel an' },
      { time: 12, text: 'Ich schreie die ganze Welt an' },
      { time: 17, text: 'Baby, warum bist du gegangen?' },
      { time: 21, text: 'Ich bin immer noch dein Mädchen' },
      { time: 25, text: 'Ich klammere mich zu fest fest' },
      { time: 30, text: 'Den Kopf in den Wolken verloren' },
      { time: 34, text: 'Nur der Himmel weiß, wo du jetzt bist' },
      { time: 42, text: 'Wie soll ich je wieder lieben?' },
      { time: 50, text: 'Wie soll ich je wieder vertrauen?' },
      { time: 59, text: 'Ich bleibe die ganze Nacht wach, rede mir ein, es geht mir gut' },
      { time: 67, text: 'Baby, man sieht dich nur schwerer als die meisten' },
      { time: 75, text: 'Ich lege die Platte auf und warte auf unser Lied' },
      { time: 84, text: 'Jede Nacht tanze ich mit deinem Geist' },
      { time: 92, text: 'Jede Nacht tanze ich mit deinem Geist' },
      { time: 101, text: 'Ich hatte nie die Chance' },
      { time: 105, text: 'Einen letzten Abschied zu nehmen' },
      { time: 110, text: 'Ich muss weitermachen' },
      { time: 114, text: 'Aber der Versuch tut so weh' },
      { time: 122, text: 'Wie soll ich je wieder lieben?' },
      { time: 131, text: 'Wie soll ich je wieder vertrauen?' },
      { time: 139, text: 'Die ganze Nacht wach, mir einredend, es sei okay' },
      { time: 148, text: 'Du bist nur unsichtbarer als alle anderen' },
      { time: 156, text: 'Ich starte die Platte, warte auf unseren Song' },
      { time: 165, text: 'Jede Nacht tanze ich mit deinem Geist' },
      { time: 173, text: 'Jede Nacht tanze ich mit deinem Geist' },
    ],
    ko: [
      { time: 0, text: '♪ (애절한 어쿠스틱 인트로) ♪' },
      { time: 8, text: '하늘을 향해 소리쳐' },
      { time: 12, text: '세상을 향해 비명을 질러' },
      { time: 17, text: '그대여, 왜 떠나간 거야?' },
      { time: 21, text: '난 여전히 너의 연인인데' },
      { time: 25, text: '너무 꽉 붙잡고 있어' },
      { time: 30, text: '머릿속은 온통 구름 위를 헤매' },
      { time: 34, text: '네가 지금 어디에 있는지 오직 하늘만이 알겠지' },
      { time: 42, text: '어떻게 다시 사랑해야 할까?' },
      { time: 50, text: '어떻게 다시 누군가를 믿어야 할까?' },
      { time: 59, text: '밤새 깨어 있으면서, 난 괜찮다고 스스로를 달래' },
      { time: 67, text: '그대여, 넌 그저 다른 이들보다 보기 어려울 뿐이야' },
      { time: 75, text: '음반을 틀고, 우리의 노래가 나오길 기다려' },
      { time: 84, text: '매일 밤, 난 너의 유령과 춤을 춰' },
      { time: 92, text: '매일 밤, 난 너의 그림자와 춤을 춰' },
      { time: 101, text: '기회조차 없었어' },
      { time: 105, text: '마지막 작별 인사를 건넬' },
      { time: 110, text: '앞으로 나아가야 하는데' },
      { time: 114, text: '노력할수록 가슴이 너무 아파' },
      { time: 122, text: '어떻게 다시 사랑을 시작할 수 있을까?' },
      { time: 131, text: '어떻게 다시 믿음을 가질 수 있을까?' },
      { time: 139, text: '온 밤을 지새우며 괜찮다고 속삭여' },
      { time: 148, text: '너는 단지 조금 더 숨어있는 것뿐이라고' },
      { time: 156, text: '레코드를 올리고 우리의 멜로디를 기다리지' },
      { time: 165, text: '매일 밤, 난 너의 영혼과 춤을 춰' },
      { time: 173, text: '매일 밤, 난 너의 유령과 함께 춤을 춰' },
    ],
  },

  // 4. Love In The Dark - Adele
  'song-1788803603766': {
    en: [
      { time: 0, text: '♪ (Soft cinematic piano chords) ♪' },
      { time: 8, text: 'Take your eyes off of me so I can leave' },
      { time: 15, text: "I'm far too ashamed to do it with you watching me" },
      { time: 22, text: 'This is never ending, we have been here before' },
      { time: 29, text: "But I can't stay this time, 'cause I don't love you anymore" },
      { time: 37, text: 'Please, stay where you are, don\'t come any closer' },
      { time: 44, text: "Don't try to change my mind, I'm being cruel to be kind" },
      { time: 51, text: "I can't love you in the dark" },
      { time: 58, text: "It feels like we're oceans apart" },
      { time: 65, text: 'There is so much space between us' },
      { time: 72, text: "Baby, we're already defeated" },
      { time: 79, text: 'Everything changed me' },
      { time: 86, text: "You have given me something that I can't live without" },
      { time: 94, text: "You mustn't underestimate that when you are in doubt" },
      { time: 101, text: "But I don't want to carry on like everything is fine" },
      { time: 108, text: 'The longer we ignore it, all the more that we will fight' },
      { time: 116, text: "Please, don't fall apart, I can't face your breaking heart" },
      { time: 123, text: "I'm trying to be brave, stop asking me to stay" },
      { time: 130, text: "I can't love you in the dark" },
      { time: 137, text: "It feels like we're oceans apart" },
      { time: 144, text: 'There is so much space between us' },
      { time: 151, text: "Baby, we're already defeated" },
      { time: 158, text: 'Everything changed me' },
      { time: 167, text: "And I don't think you can save me" },
    ],
    es: [
      { time: 0, text: '♪ (Acordes cinematográficos de piano) ♪' },
      { time: 8, text: 'Aparta tus ojos de mí para que pueda irme' },
      { time: 15, text: 'Siento demasiada vergüenza de hacerlo mientras me miras' },
      { time: 22, text: 'Esto nunca termina, ya hemos estado aquí antes' },
      { time: 29, text: 'Pero no puedo quedarme esta vez, porque ya no te amo' },
      { time: 37, text: 'Por favor, quédate donde estás, no te acerques más' },
      { time: 44, text: 'No intentes hacerme cambiar de opinión, soy cruel para ser compasiva' },
      { time: 51, text: 'No puedo amarte en la oscuridad' },
      { time: 58, text: 'Se siente como si estuviéramos a océanos de distancia' },
      { time: 65, text: 'Hay demasiado espacio entre nosotros' },
      { time: 72, text: 'Cariño, ya estamos derrotados' },
      { time: 79, text: 'Todo me cambió' },
      { time: 86, text: 'Me has dado algo sin lo que no puedo vivir' },
      { time: 94, text: 'No debes subestimar eso cuando tengas dudas' },
      { time: 101, text: 'Pero no quiero seguir fingiendo que todo está bien' },
      { time: 108, text: 'Cuanto más lo ignoremos, más pelearemos' },
      { time: 116, text: 'Por favor, no te derrumbes, no puedo soportar ver tu corazón romperse' },
      { time: 123, text: 'Estoy intentando ser valiente, deja de pedirme que me quede' },
      { time: 130, text: 'No puedo amarte en la oscuridad' },
      { time: 137, text: 'Se siente como si estuviéramos a océanos de distancia' },
      { time: 144, text: 'Hay tanto espacio entre los dos' },
      { time: 151, text: 'Cariño, ya fuimos vencidos' },
      { time: 158, text: 'Todo me transformó' },
      { time: 167, text: 'Y no creo que puedas salvarme' },
    ],
    tl: [
      { time: 0, text: '♪ (Banayad na tunog ng piyano) ♪' },
      { time: 8, text: 'Ialis mo ang iyong tingin sa akin upang ako ay makaalis' },
      { time: 15, text: 'Labis akong nahihiyang gawin ito habang nakatingin ka' },
      { time: 22, text: 'Wala itong katapusan, nandito na tayo noon' },
      { time: 29, text: 'Ngunit hindi ako makakatagal ngayon, dahil hindi na kita mahal' },
      { time: 37, text: 'Pakiusap, manatili ka riyan, huwag ka nang lumapit' },
      { time: 44, text: 'Huwag mong subukang baguhin ang isip ko, nagpapakatatag lang ako' },
      { time: 51, text: 'Hindi kita kayang mahalin sa dilim' },
      { time: 58, text: 'Tila karagatan ang layo natin sa isa\'t isa' },
      { time: 65, text: 'Napakalaki ng espasyo sa pagitan natin' },
      { time: 72, text: 'Mahal, talo na tayo sa labang ito' },
      { time: 79, text: 'Binago ako ng lahat' },
      { time: 86, text: 'Binigyan mo ako ng bagay na di ko kayang mabuhay nang wala ito' },
      { time: 94, text: 'Huwag mong mamaliitin iyon kapag ikaw ay nagdududa' },
      { time: 101, text: 'Ngunit ayaw ko nang magpanggap na maayos ang lahat' },
      { time: 108, text: 'Habang mas binabalewala natin, lalo lang tayong magtatalo' },
      { time: 116, text: 'Pakiusap, huwag kang mawalan ng pag-asa, di ko kayang makitang durog ka' },
      { time: 123, text: 'Sinusubukan kong maging matapang, huwag mo na akong pakiusapang manatili' },
      { time: 130, text: 'Hindi kita kayang mahalin sa dilim' },
      { time: 137, text: 'Para tayong pinaghihiwalay ng karagatan' },
      { time: 144, text: 'Napakalayo natin sa isa\'t isa' },
      { time: 151, text: 'Mahal, talo na tayo bago pa man magsimula' },
      { time: 158, text: 'Binago ako ng lahat' },
      { time: 167, text: 'At sa palagay ko hindi mo na ako maililigtas' },
    ],
    ja: [
      { time: 0, text: '♪ (静謐なシネマティックピアノ) ♪' },
      { time: 8, text: '私から目をそらして、立ち去れるように' },
      { time: 15, text: 'あなたに見つめられたまま去るなんて、あまりに惨めだから' },
      { time: 22, text: '終わりのない繰り返し、前にもここにいたわ' },
      { time: 29, text: 'でも今回は残れない、もうあなたを愛していないから' },
      { time: 37, text: 'お願い、そこにいて、これ以上近づかないで' },
      { time: 44, text: '考え直させようとしないで、優しさのために冷たくしているの' },
      { time: 51, text: '暗闇の中であなたを愛することはできない' },
      { time: 58, text: 'まるで海を隔てているかのように遠く感じる' },
      { time: 65, text: 'ふたりの間には広すぎる隙間があるの' },
      { time: 72, text: 'ねえ、私たちはもう敗北している' },
      { time: 79, text: 'すべてが私を変えてしまった' },
      { time: 86, text: 'あなたは私になくてはならないものをくれた' },
      { time: 94, text: '迷ったときでも、その価値を決して見くびらないで' },
      { time: 101, text: 'でも何事もないかのように続けるのはもう嫌なの' },
      { time: 108, text: '無視し続けるほど、私たちは争うことになる' },
      { time: 116, text: 'お願い、崩れ落ちないで、あなたの傷つく姿を見たくない' },
      { time: 123, text: '勇敢であろうとしているの、引き止めないで' },
      { time: 130, text: '暗闇の中では愛せないの' },
      { time: 137, text: '海のように遠く離れてしまった' },
      { time: 144, text: 'ふたりの隙間は埋まらない' },
      { time: 151, text: '私たちはすでに負けてしまったの' },
      { time: 158, text: 'すべてが私を変えた' },
      { time: 167, text: 'もうあなたにも私を救えないと思う' },
    ],
    fr: [
      { time: 0, text: '♪ (Accords de piano cinématographiques) ♪' },
      { time: 8, text: 'Détourne tes yeux de moi pour que je puisse partir' },
      { time: 15, text: "J'ai bien trop honte de le faire sous ton regard" },
      { time: 22, text: "C'est sans fin, nous avons déjà vécu cela" },
      { time: 29, text: "Mais je ne peux rester cette fois, car je ne t'aime plus" },
      { time: 37, text: "S'il te plaît, reste où tu es, n'approche pas plus" },
      { time: 44, text: "N'essaie pas de me faire changer d'avis, je suis dure pour être juste" },
      { time: 51, text: "Je ne peux pas t'aimer dans le noir" },
      { time: 58, text: "J'ai l'impression qu'un océan nous sépare" },
      { time: 65, text: "Il y a tant d'espace entre nous" },
      { time: 72, text: "Bébé, nous sommes déjà vaincus" },
      { time: 79, text: 'Tout m’a changée' },
      { time: 86, text: "Tu m'as donné quelque chose sans lequel je ne peux vivre" },
      { time: 94, text: "Tu ne dois pas sous-estimer cela quand tu doutes" },
      { time: 101, text: "Mais je refuse de faire comme si tout allait bien" },
      { time: 108, text: "Plus nous l'ignorons, plus nous nous déchirons" },
      { time: 116, text: "Ne t'effondre pas, je ne supporterais pas ton cœur brisé" },
      { time: 123, text: "J'essaie d'être courageuse, cesse de me supplier de rester" },
      { time: 130, text: "Je ne peux pas t'aimer dans l'obscurité" },
      { time: 137, text: "C'est comme si un océan nous séparait" },
      { time: 144, text: "Il y a tant de distance entre nous" },
      { time: 151, text: 'Nous avons déjà perdu cette bataille' },
      { time: 158, text: 'Tout a changé en moi' },
      { time: 167, text: "Et je ne crois pas que tu puisses me sauver" },
    ],
    de: [
      { time: 0, text: '♪ (Sanfte filmreife Klavierakkorde) ♪' },
      { time: 8, text: 'Wende deinen Blick von mir ab, damit ich gehen kann' },
      { time: 15, text: 'Ich schäme mich zu sehr, es vor deinen Augen zu tun' },
      { time: 22, text: 'Das nimmt kein Ende, wir waren schon einmal hier' },
      { time: 29, text: 'Doch dieses Mal kann ich nicht bleiben, weil ich dich nicht mehr liebe' },
      { time: 37, text: 'Bitte bleib stehen, wo du bist, komm nicht näher' },
      { time: 44, text: 'Versuch nicht, mich umzustimmen, ich muss grausam sein, um ehrlich zu sein' },
      { time: 51, text: 'Ich kann dich nicht im Dunkeln lieben' },
      { time: 58, text: 'Es fühlt sich an, als lägen Ozeane zwischen uns' },
      { time: 65, text: 'Da ist so viel Leere zwischen uns beiden' },
      { time: 72, text: 'Baby, wir haben diesen Kampf längst verloren' },
      { time: 79, text: 'Alles hat mich verändert' },
      { time: 86, text: 'Du hast mir etwas gegeben, ohne das ich nicht leben kann' },
      { time: 94, text: 'Unterschätze das nicht, wenn du zweifelst' },
      { time: 101, text: 'Aber ich will nicht so tun, als wäre alles in Ordnung' },
      { time: 108, text: 'Je länger wir es totschweigen, desto mehr streiten wir' },
      { time: 116, text: 'Bitte brich nicht zusammen, ich ertrage dein gebrochenes Herz nicht' },
      { time: 123, text: 'Ich versuche tapfer zu sein, bitte mich nicht zu bleiben' },
      { time: 130, text: 'Ich kann dich nicht im Schatten lieben' },
      { time: 137, text: 'Es fühlt sich an wie endlose Meere' },
      { time: 144, text: 'So viel Raum zwischen unseren Seelen' },
      { time: 151, text: 'Wir sind bereits geschlagen' },
      { time: 158, text: 'Alles hat mich gewandelt' },
      { time: 167, text: 'Und ich glaube nicht, dass du mich retten kannst' },
    ],
    ko: [
      { time: 0, text: '♪ (고요하고 영화 같은 피아노 선율) ♪' },
      { time: 8, text: '내가 떠날 수 있게 네 시선을 거두어줘' },
      { time: 15, text: '네가 지켜보는 앞에서 떠나기엔 너무 부끄러우니까' },
      { time: 22, text: '끝나지 않는 굴레, 우린 전에도 이러했지' },
      { time: 29, text: '하지만 이번엔 머물 수 없어, 더는 널 사랑하지 않으니까' },
      { time: 37, text: '제발 거기 서 있어 줘, 더는 다가오지 마' },
      { time: 44, text: '내 마음을 돌리려 하지 마, 진심을 위해 독해지는 거야' },
      { time: 51, text: '어둠 속에서 널 사랑할 순 없어' },
      { time: 58, text: '마치 바다만큼 멀리 떨어진 것 같아' },
      { time: 65, text: '우리 사이엔 너무 큰 간극이 있어' },
      { time: 72, text: '그대여, 우린 이미 패배했어' },
      { time: 79, text: '모든 것이 날 바꾸어 놓았지' },
      { time: 86, text: '넌 내게 없어서는 안 될 소중한 것을 주었어' },
      { time: 94, text: '의심이 들 때도 그 사실을 잊지는 마' },
      { time: 101, text: '하지만 다 괜찮은 척 계속 버티고 싶진 않아' },
      { time: 108, text: '외면할수록 우린 더 상처 입고 싸울 테니까' },
      { time: 116, text: '제발 무너지지 마, 네 찢어지는 마음을 마주할 자신이 없어' },
      { time: 123, text: '난 용기를 내고 있어, 머물러 달라고 붙잡지 마' },
      { time: 130, text: '어둠 속에선 널 품을 수 없어' },
      { time: 137, text: '우린 마치 대양만큼이나 멀어진 것 같아' },
      { time: 144, text: '우리 사이에 가로놓인 너무 많은 빈자리' },
      { time: 151, text: '우린 이미 져버린 사랑이야' },
      { time: 158, text: '모든 것이 날 바꾸었어' },
      { time: 167, text: '그리고 이젠 너도 날 구할 수 없다고 생각해' },
    ],
  },

  // 5. Night Drive - Aurora Wave
  'song-night-drive': {
    en: [
      { time: 0, text: '♪ (Atmospheric synth intro) ♪' },
      { time: 15, text: 'Cruising past the neon glow' },
      { time: 22, text: 'Watching shadows in the rear-view grow' },
      { time: 30, text: 'City skyline burning bright' },
      { time: 37, text: 'Guided only by the midnight light' },
      { time: 45, text: "We're alive in the slipstream" },
      { time: 52, text: 'Living out this electric dream' },
      { time: 60, text: 'Feel the bass underneath the wheels' },
      { time: 67, text: 'This is how the night time feels' },
      { time: 75, text: 'Night drive, across the endless line' },
      { time: 82, text: 'Lost inside this space and time' },
      { time: 90, text: 'Night drive, forever on the run' },
      { time: 97, text: 'Racing toward the morning sun' },
    ],
    es: [
      { time: 0, text: '♪ (Intro atmosférico de sintetizador) ♪' },
      { time: 15, text: 'Avanzando entre el resplandor de neón' },
      { time: 22, text: 'Mirando crecer las sombras en el retrovisor' },
      { time: 30, text: 'El horizonte de la ciudad ardiendo brillante' },
      { time: 37, text: 'Guiados solo por la luz de medianoche' },
      { time: 45, text: 'Estamos vivos en la corriente' },
      { time: 52, text: 'Viviendo este sueño eléctrico' },
      { time: 60, text: 'Siente los graves bajo las ruedas' },
      { time: 67, text: 'Así se siente la noche' },
      { time: 75, text: 'Viaje nocturno, a través de la línea infinita' },
      { time: 82, text: 'Perdidos en este espacio y tiempo' },
      { time: 90, text: 'Viaje nocturno, siempre en movimiento' },
      { time: 97, text: 'Corriendo hacia el sol naciente' },
    ],
    tl: [
      { time: 0, text: '♪ (Mahiwagang synth intro) ♪' },
      { time: 15, text: 'Bumabagtas lampas sa kislap ng neon' },
      { time: 22, text: 'Pinagmamasdan ang anino sa salamin' },
      { time: 30, text: 'Abot-tanaw ng lungsod na nagliliyab' },
      { time: 37, text: 'Gabay lamang ang liwanag ng hatinggabi' },
      { time: 45, text: 'Buhay tayo sa hangin ng kalsada' },
      { time: 52, text: 'Isinasabuhay ang de-kuryenteng panaginip' },
      { time: 60, text: 'Damhin ang bass sa ilalim ng gulong' },
      { time: 67, text: 'Ito ang tunay na damdamin ng gabi' },
      { time: 75, text: 'Biyaheng gabi, sa walang katapusang guhit' },
      { time: 82, text: 'Naliligaw sa puwang at panahong ito' },
      { time: 90, text: 'Biyaheng gabi, habang-buhay na tumatakbo' },
      { time: 97, text: 'Humaharurot patungo sa sumisikat na araw' },
    ],
    ja: [
      { time: 0, text: '♪ (幻想的なシンセイントロ) ♪' },
      { time: 15, text: 'ネオンの輝きを追い抜いていく' },
      { time: 22, text: 'バックミラーに伸びる影を見つめながら' },
      { time: 30, text: 'きらめく摩天楼の夜景' },
      { time: 37, text: '真夜中の光だけを道標にして' },
      { time: 45, text: '風の流れの中で今を生きている' },
      { time: 52, text: 'エレクトリックな夢を駆け抜けて' },
      { time: 60, text: 'タイヤの底から伝わる重低音' },
      { time: 67, text: 'これこそが夜の鼓動' },
      { time: 75, text: 'ナイトドライブ、果てなき直線道路' },
      { time: 82, text: '時空の迷路に溶け込んで' },
      { time: 90, text: 'ナイトドライブ、どこまでも走り続ける' },
      { time: 97, text: '昇る朝日を目指して疾走する' },
    ],
    fr: [
      { time: 0, text: '♪ (Intro atmosphérique au synthétiseur) ♪' },
      { time: 15, text: 'Roulant à travers la lueur des néons' },
      { time: 22, text: 'Regardant les ombres grandir dans le rétro' },
      { time: 30, text: 'La skyline illuminée de mille feux' },
      { time: 37, text: 'Guidés seulement par la lueur de minuit' },
      { time: 45, text: "Vivants au cœur de l'aspiration" },
      { time: 52, text: 'Vivant ce rêve électrique' },
      { time: 60, text: 'Ressens les basses sous les roues' },
      { time: 67, text: "C'est ainsi que vibre la nuit" },
      { time: 75, text: 'Traversée nocturne, sur la ligne sans fin' },
      { time: 82, text: 'Perdus dans cet espace-temps' },
      { time: 90, text: 'Virée de nuit, en fuite éternelle' },
      { time: 97, text: 'Filant droit vers le soleil levant' },
    ],
    de: [
      { time: 0, text: '♪ (Atmosphärisches Synth-Intro) ♪' },
      { time: 15, text: 'Gleite vorbei am Neonglanz' },
      { time: 22, text: 'Beobachte, wie die Schatten im Rückspiegel wachsen' },
      { time: 30, text: 'Die Skyline der Stadt strahlt hell' },
      { time: 37, text: 'Geleitet nur vom Licht der Mitternacht' },
      { time: 45, text: 'Wir leben im Windschatten' },
      { time: 52, text: 'Leben diesen elektrischen Traum' },
      { time: 60, text: 'Spüre den Bass unter den Rädern' },
      { time: 67, text: 'So fühlt sich die Nacht an' },
      { time: 75, text: 'Nachtfahrt über die endlose Straße' },
      { time: 82, text: 'Verloren in Raum und Zeit' },
      { time: 90, text: 'Nachtfahrt, für immer unterwegs' },
      { time: 97, text: 'Der Morgensonne entgegen' },
    ],
    ko: [
      { time: 0, text: '♪ (몽환적인 신스 인트로) ♪' },
      { time: 15, text: '네온 불빛을 가르며 달리는 밤' },
      { time: 22, text: '백미러 속 길어지는 그림자를 보며' },
      { time: 30, text: '환하게 불타오르는 도시의 스카이라인' },
      { time: 37, text: '오직 자정의 불빛만을 길잡이 삼아' },
      { time: 45, text: '우린 바람 속에서 살아 숨 쉬고 있어' },
      { time: 52, text: '이 일렉트릭 꿈속을 달리며' },
      { time: 60, text: '바퀴 아래로 전해지는 베이스의 울림' },
      { time: 67, text: '이것이 바로 밤이 건네는 느낌' },
      { time: 75, text: '나이트 드라이브, 끝없는 지평선을 넘어' },
      { time: 82, text: '이 시공간 속에 흠뻑 빠져들어' },
      { time: 90, text: '나이트 드라이브, 영원히 멈추지 않는 질주' },
      { time: 97, text: '아침 해를 향해 속도를 높여' },
    ],
  },

  // 6. Velvet Touch - Silk & Soul
  'song-velvet-touch': {
    en: [
      { time: 0, text: '♪ (Soft Fender Rhodes intro) ♪' },
      { time: 12, text: "Whisper slow, don't rush the night" },
      { time: 18, text: 'Everything feels just right' },
      { time: 25, text: 'Your silhouette against the wall' },
      { time: 31, text: 'Every time you softly call' },
      { time: 38, text: 'Velvet touch on my skin' },
      { time: 44, text: "That's where all the magic begins" },
      { time: 51, text: 'Velvet touch, take my hand' },
      { time: 57, text: 'No one else could understand' },
    ],
    es: [
      { time: 0, text: '♪ (Intro suave de Fender Rhodes) ♪' },
      { time: 12, text: 'Susurra despacio, no apresures la noche' },
      { time: 18, text: 'Todo se siente perfecto' },
      { time: 25, text: 'Tu silueta dibujada en la pared' },
      { time: 31, text: 'Cada vez que me llamas suavemente' },
      { time: 38, text: 'Tacto de terciopelo en mi piel' },
      { time: 44, text: 'Ahí es donde comienza toda la magia' },
      { time: 51, text: 'Tacto de terciopelo, toma mi mano' },
      { time: 57, text: 'Nadie más podría comprender' },
    ],
    tl: [
      { time: 0, text: '♪ (Mahinahong intro ng Fender Rhodes) ♪' },
      { time: 12, text: 'Dahan-dahang bumulong, huwag madaliin ang gabi' },
      { time: 18, text: 'Ang lahat ay napakaganda at tama' },
      { time: 25, text: 'Ang anino mo sa dingding' },
      { time: 31, text: 'Tuwing tatawag ka nang marahan' },
      { time: 38, text: 'Haplos ng pelus sa aking balat' },
      { time: 44, text: 'Doon nagsisimula ang hiwaga' },
      { time: 51, text: 'Haplos ng pelus, hawakan ang aking kamay' },
      { time: 57, text: 'Walang iba ang makakaunawa' },
    ],
    ja: [
      { time: 0, text: '♪ (柔らかなローズピアノのイントロ) ♪' },
      { time: 12, text: 'ゆっくり囁いて、夜を急がないで' },
      { time: 18, text: 'すべてが心地よく溶け合っていく' },
      { time: 25, text: '壁に映るあなたのシルエット' },
      { time: 31, text: '優しく名前を呼ばれるたび' },
      { time: 38, text: '肌に触れるベルベットの温もり' },
      { time: 44, text: 'そこからすべての魔法が始まる' },
      { time: 51, text: 'ベルベットタッチ、手を取って' },
      { time: 57, text: '他の誰にも分からないふたりだけの世界' },
    ],
    fr: [
      { time: 0, text: '♪ (Douce intro Fender Rhodes) ♪' },
      { time: 12, text: 'Chuchote lentement, ne presse pas la nuit' },
      { time: 18, text: 'Tout semble si parfait' },
      { time: 25, text: 'Ta silhouette dessinée contre le mur' },
      { time: 31, text: 'Chaque fois que tu m’appelles doucement' },
      { time: 38, text: 'Une touche de velours sur ma peau' },
      { time: 44, text: 'C’est là que toute la magie commence' },
      { time: 51, text: 'Touche de velours, prends ma main' },
      { time: 57, text: 'Personne d’autre ne pourrait comprendre' },
    ],
    de: [
      { time: 0, text: '♪ (Sanftes Fender Rhodes Intro) ♪' },
      { time: 12, text: 'Flüstere leise, beeile die Nacht nicht' },
      { time: 18, text: 'Alles fühlt sich genau richtig an' },
      { time: 25, text: 'Deine Silhouette an der Wand' },
      { time: 31, text: 'Jedes Mal, wenn du leise rufst' },
      { time: 38, text: 'Samtene Berührung auf meiner Haut' },
      { time: 44, text: 'Dort beginnt die ganze Magie' },
      { time: 51, text: 'Samtene Berührung, nimm meine Hand' },
      { time: 57, text: 'Niemand sonst könnte das verstehen' },
    ],
    ko: [
      { time: 0, text: '♪ (부드러운 로즈 피아노 인트로) ♪' },
      { time: 12, text: '천천히 속삭여줘, 밤을 서두르지 마' },
      { time: 18, text: '모든 것이 완벽하게 느껴져' },
      { time: 25, text: '벽에 비치는 너의 실루엣' },
      { time: 31, text: '네가 나를 다정하게 부를 때마다' },
      { time: 38, text: '내 살결에 닿는 벨벳 같은 감촉' },
      { time: 44, text: '모든 마법은 바로 거기서 시작돼' },
      { time: 51, text: '벨벳의 손길, 내 손을 잡아줘' },
      { time: 57, text: '그 누구도 이해하지 못할 우리만의 순간' },
    ],
  },

  // 7. Tokyo Drizzle - Lofi Dreamer
  'song-tokyo-drizzle': {
    en: [
      { time: 0, text: '♪ (Vinyl crackle and gentle rain ambiance) ♪' },
      { time: 15, text: '♪ (Mellow jazz piano riff begins) ♪' },
      { time: 45, text: '♪ (Soft drum groove enters with brush snare) ♪' },
      { time: 75, text: 'Rain drops falling on the neon streets' },
      { time: 105, text: 'Echoes of footsteps and quiet beats' },
      { time: 135, text: '♪ (Rain sounds fade out into peace) ♪' },
    ],
    es: [
      { time: 0, text: '♪ (Crujido de vinilo y lluvia suave de fondo) ♪' },
      { time: 15, text: '♪ (Comienza el suave riff de piano jazz) ♪' },
      { time: 45, text: '♪ (Entra la batería suave con escobillas) ♪' },
      { time: 75, text: 'Gotas de lluvia cayendo en las calles de neón' },
      { time: 105, text: 'Ecos de pasos y ritmos silenciosos' },
      { time: 135, text: '♪ (El sonido de lluvia se desvanece en paz) ♪' },
    ],
    tl: [
      { time: 0, text: '♪ (Lagitik ng plaka at mahinang ulan) ♪' },
      { time: 15, text: '♪ (Nagsisimula ang banayad na jazz piano) ♪' },
      { time: 45, text: '♪ (Pumapasok ang malumanay na tunog ng tambol) ♪' },
      { time: 75, text: 'Mga patak ng ulan sa mga kalyeng may neon' },
      { time: 105, text: 'Alingawngaw ng yabag at banayad na tugtog' },
      { time: 135, text: '♪ (Unti-unting humuhupa ang ulan sa kapayapaan) ♪' },
    ],
    ja: [
      { time: 0, text: '♪ (レコードの針音と優しい雨の音) ♪' },
      { time: 15, text: '♪ (心地よいジャズピアノの旋律が響く) ♪' },
      { time: 45, text: '♪ (ブラシアクションの柔らかなドラム) ♪' },
      { time: 75, text: 'ネオンの街並みに降り注ぐ雨粒' },
      { time: 105, text: '濡れたアスファルトに響く足音と静かなビート' },
      { time: 135, text: '♪ (雨音とともに穏やかにフェードアウト) ♪' },
    ],
    fr: [
      { time: 0, text: '♪ (Crachotement de vinyle et douce pluie) ♪' },
      { time: 15, text: '♪ (Le doux riff de piano jazz commence) ♪' },
      { time: 45, text: '♪ (Entrée d’une batterie feutrée aux balais) ♪' },
      { time: 75, text: 'Gouttes de pluie tombant sur les avenues éclairées de néons' },
      { time: 105, text: 'Échos de pas et rythmes paisibles' },
      { time: 135, text: '♪ (La pluie s’estompe dans la sérénité) ♪' },
    ],
    de: [
      { time: 0, text: '♪ (Vinylknistern und sanftes Regenrauschen) ♪' },
      { time: 15, text: '♪ (Sanftes Jazz-Klavier beginnt) ♪' },
      { time: 45, text: '♪ (Sanfter Besen-Schlagzeug-Groove setzt ein) ♪' },
      { time: 75, text: 'Regentropfen fallen auf die Neonstraßen' },
      { time: 105, text: 'Schritte verhallen zu leisen Beats' },
      { time: 135, text: '♪ (Regenklänge verklingen friedlich) ♪' },
    ],
    ko: [
      { time: 0, text: '♪ (바이닐 노이즈와 잔잔한 빗소리 앰비언스) ♪' },
      { time: 15, text: '♪ (감미로운 재즈 피아노 선율이 시작됨) ♪' },
      { time: 45, text: '♪ (브러시 드럼의 나지막한 그루브 시작) ♪' },
      { time: 75, text: '네온 번쩍이는 거리에 떨어지는 빗방울들' },
      { time: 105, text: '발걸음의 메아리와 조용한 비트' },
      { time: 135, text: '♪ (빗소리가 평화 속으로 잦아듦) ♪' },
    ],
  },

  // 8. Starlight Glow - Nova Pulse
  'song-starlight-glow': {
    en: [
      { time: 0, text: '♪ (Sparkling synth arpeggio) ♪' },
      { time: 10, text: 'Look up at the ceiling of stars' },
      { time: 16, text: 'Forget about who we are' },
      { time: 22, text: 'Tonight the universe is ours' },
      { time: 28, text: 'Dancing in the starlight glow' },
      { time: 34, text: 'Feel the rhythm take control' },
      { time: 40, text: 'Everywhere we want to go' },
      { time: 46, text: 'Starlight glow, shining down' },
      { time: 52, text: 'Brightest light in all this town!' },
    ],
    es: [
      { time: 0, text: '♪ (Brillante arpegio de sintetizador) ♪' },
      { time: 10, text: 'Mira hacia arriba al techo de estrellas' },
      { time: 16, text: 'Olvida quiénes somos' },
      { time: 22, text: 'Esta noche el universo es nuestro' },
      { time: 28, text: 'Bailando bajo el resplandor de las estrellas' },
      { time: 34, text: 'Siente el ritmo tomar el control' },
      { time: 40, text: 'A donde sea que queramos ir' },
      { time: 46, text: 'Brillo estelar, resplandeciendo' },
      { time: 52, text: '¡La luz más brillante de toda esta ciudad!' },
    ],
    tl: [
      { time: 0, text: '♪ (Kumukutikutap na synth arpeggio) ♪' },
      { time: 10, text: 'Tumingala sa bubong ng mga bituin' },
      { time: 16, text: 'Limutin kung sino man tayo' },
      { time: 22, text: 'Ngayong gabi, atin ang sanlibutan' },
      { time: 28, text: 'Sumasayaw sa kislap ng mga bituin' },
      { time: 34, text: 'Damhin ang ritmo na nagpapasigla' },
      { time: 40, text: 'Saan man natin naisin pumunta' },
      { time: 46, text: 'Kislap ng bituin, bumababa sa atin' },
      { time: 52, text: 'Pinakamaliwanag na ilaw sa buong bayan!' },
    ],
    ja: [
      { time: 0, text: '♪ (きらめくシンセアルペジオ) ♪' },
      { time: 10, text: '星空の天井を見上げてごらん' },
      { time: 16, text: '自分が誰かなんて忘れてしまおう' },
      { time: 22, text: '今夜、宇宙は私たちのもの' },
      { time: 28, text: '星の光の輝きの中で踊ろう' },
      { time: 34, text: 'リズムにすべてを委ねて' },
      { time: 40, text: '行きたい場所へどこまでも' },
      { time: 46, text: '降り注ぐ星あかりのグロウ' },
      { time: 52, text: 'この街でいちばん眩しい光！' },
    ],
    fr: [
      { time: 0, text: '♪ (Arpèges scintillants au synthétiseur) ♪' },
      { time: 10, text: 'Lève les yeux vers ce dôme étoilé' },
      { time: 16, text: 'Oublions qui nous sommes' },
      { time: 22, text: "Ce soir, l'univers nous appartient" },
      { time: 28, text: 'Dansant sous la lueur des étoiles' },
      { time: 34, text: 'Sens le rythme prendre les commandes' },
      { time: 40, text: 'Partout où nous voulons voyager' },
      { time: 46, text: 'Lueur des étoiles qui rayonne' },
      { time: 52, text: 'La plus éclatante lumière de la ville !' },
    ],
    de: [
      { time: 0, text: '♪ (Funkelndes Synth-Arpeggio) ♪' },
      { time: 10, text: 'Blick hinauf zum Sternenhimmel' },
      { time: 16, text: 'Vergiss, wer wir sind' },
      { time: 22, text: 'Heute Nacht gehört das Universum uns' },
      { time: 28, text: 'Wir tanzen im Glanz der Sterne' },
      { time: 34, text: 'Spüre, wie der Rhythmus die Kontrolle übernimmt' },
      { time: 40, text: 'Wohin auch immer wir wollen' },
      { time: 46, text: 'Sternenlicht, das herabstrahlt' },
      { time: 52, text: 'Das hellste Licht in der ganzen Stadt!' },
    ],
    ko: [
      { time: 0, text: '♪ (반짝이는 신스 아르페지오) ♪' },
      { time: 10, text: '별들로 가득한 밤하늘을 올려다봐' },
      { time: 16, text: '우리가 누구인지는 잠시 잊어버려' },
      { time: 22, text: '오늘 밤 이 우주는 온전히 우리의 것' },
      { time: 28, text: '별빛의 찬란한 광채 속에 춤을 춰' },
      { time: 34, text: '리듬이 온몸을 이끌게 내버려 둬' },
      { time: 40, text: '우리가 원하는 그 어디로든' },
      { time: 46, text: '쏟아져 내리는 별빛의 찬란함' },
      { time: 52, text: '이 도시에서 가장 밝게 빛나는 빛!' },
    ],
  },

  // 9. Cyber Sunset - Neon Knight
  'song-cyber-sunset': {
    en: [
      { time: 0, text: '♪ (Retro arcade synth pulse) ♪' },
      { time: 20, text: 'Orange skies over polygon shores' },
      { time: 50, text: 'Chasing the sun behind neon doors' },
      { time: 80, text: 'Hold the wheel as the gridlines glow' },
      { time: 110, text: 'Never look back, just let it flow' },
    ],
    es: [
      { time: 0, text: '♪ (Pulso retro de sintetizador arcade) ♪' },
      { time: 20, text: 'Cielos anaranjados sobre costas poligonales' },
      { time: 50, text: 'Persiguiendo el sol tras puertas de neón' },
      { time: 80, text: 'Sujeta el volante mientras la cuadrícula brilla' },
      { time: 110, text: 'Nunca mires atrás, solo déjate llevar' },
    ],
    tl: [
      { time: 0, text: '♪ (Retro synth pulse) ♪' },
      { time: 20, text: 'Kulay kahel na langit sa ibabaw ng dalampasigan' },
      { time: 50, text: 'Hinahabol ang araw sa likod ng mga pintuang neon' },
      { time: 80, text: 'Hawakan ang manibela habang umiilaw ang kalsada' },
      { time: 110, text: 'Huwag nang lilingon, sumabay lang sa agos' },
    ],
    ja: [
      { time: 0, text: '♪ (レトロなアーケードシンセパルス) ♪' },
      { time: 20, text: 'ポリゴンの海辺に広がるオレンジ色の空' },
      { time: 50, text: 'ネオンの扉の向こう、沈む夕陽を追いかけて' },
      { time: 80, text: 'グリッドラインが光る中、ハンドルを握りしめ' },
      { time: 110, text: '決して振り返らず、ただ風のままに進め' },
    ],
    fr: [
      { time: 0, text: '♪ (Pulsations rétro arcade au synthétiseur) ♪' },
      { time: 20, text: 'Ciels orangés sur des rives polygonales' },
      { time: 50, text: 'Poursuivant le soleil derrière les portes néon' },
      { time: 80, text: 'Tiens le volant tandis que brillent les lignes du tracé' },
      { time: 110, text: 'Ne te retourne jamais, laisse simplement couler' },
    ],
    de: [
      { time: 0, text: '♪ (Retro-Arcade-Synth-Impuls) ♪' },
      { time: 20, text: 'Orangene Himmel über Polygon-Küsten' },
      { time: 50, text: 'Wir jagen der Sonne hinter Neontüren nach' },
      { time: 80, text: 'Halt das Steuer, während die Gitterlinien leuchten' },
      { time: 110, text: 'Blick nie zurück, lass es einfach fließen' },
    ],
    ko: [
      { time: 0, text: '♪ (레트로 아케이드 신스 펄스) ♪' },
      { time: 20, text: '폴리곤 해변 위로 번지는 오렌지빛 하늘' },
      { time: 50, text: '네온 문 뒤편으로 지는 태양을 쫓아' },
      { time: 80, text: '그리드 라인이 빛나는 동안 운전대를 굳게 잡아' },
      { time: 110, text: '뒤돌아보지 마, 그저 흘러가게 둬' },
    ],
  },

  // 10. After Hours - Midnight Quartet
  'song-after-hours': {
    en: [
      { time: 0, text: '♪ (Subtle double bass and brushed snare) ♪' },
      { time: 30, text: 'The crowd is gone, the bar is closed' },
      { time: 60, text: 'In smoky shadows softly composed' },
      { time: 90, text: 'One last solo under amber light' },
      { time: 120, text: 'Saying goodbye to another night' },
    ],
    es: [
      { time: 0, text: '♪ (Contrabajo sutil y batería de escobillas) ♪' },
      { time: 30, text: 'La multitud se fue, el bar ha cerrado' },
      { time: 60, text: 'Entre sombras de humo suavemente compuestas' },
      { time: 90, text: 'Un último solo bajo la luz ámbar' },
      { time: 120, text: 'Diciéndole adiós a otra noche' },
    ],
    tl: [
      { time: 0, text: '♪ (Banayad na double bass at tambol) ♪' },
      { time: 30, text: 'Umalis na ang mga tao, sarado na ang bar' },
      { time: 60, text: 'Sa mausok na lilim ng katahimikan' },
      { time: 90, text: 'Huling tugtugin sa ilalim ng dilaw na ilaw' },
      { time: 120, text: 'Nagpapaalam sa isa na namang gabi' },
    ],
    ja: [
      { time: 0, text: '♪ (ウッドベースとブラシアクションの優しい響き) ♪' },
      { time: 30, text: '客足は途絶え、バーの灯りは落ちた' },
      { time: 60, text: '煙の漂う影の中に紡がれる旋律' },
      { time: 90, text: '琥珀色の光の下、最後のソロ' },
      { time: 120, text: 'またひとつの夜に別れを告げて' },
    ],
    fr: [
      { time: 0, text: '♪ (Contrebasse subtile et caisse claire aux balais) ♪' },
      { time: 30, text: 'La foule est partie, le bar est fermé' },
      { time: 60, text: 'Dans les ombres brumeuses doucement composées' },
      { time: 90, text: 'Un dernier solo sous une lueur ambrée' },
      { time: 120, text: 'Faisant ses adieux à une autre nuit' },
    ],
    de: [
      { time: 0, text: '♪ (Subtiler Kontrabass und Besen-Snare) ♪' },
      { time: 30, text: 'Die Menge ist fort, die Bar schließt ihre Türen' },
      { time: 60, text: 'In rauchigen Schatten sanft komponiert' },
      { time: 90, text: 'Ein letztes Solo unter bernsteinfarbenem Schein' },
      { time: 120, text: 'Abschied von einer weiteren Nacht' },
    ],
    ko: [
      { time: 0, text: '♪ (은은한 콘트라베이스와 브러시 스네어) ♪' },
      { time: 30, text: '손님들은 모두 떠나고, 바의 문은 닫혔어' },
      { time: 60, text: '자욱한 담배 연기 속 나직이 흐르는 선율' },
      { time: 90, text: '호박빛 조명 아래 마지막 솔로 연주' },
      { time: 120, text: '또 하나의 깊은 밤에게 건네는 작별 인사' },
    ],
  },

  // 11. Study Session - ChillHop Academy
  'song-study-session': {
    en: [
      { time: 0, text: '♪ (Warm tape loop and mellow keys) ♪' },
      { time: 25, text: 'Pencil scratching on the paper page' },
      { time: 55, text: 'Thoughts drift away from center stage' },
      { time: 85, text: 'Coffee in the mug is turning cold' },
      { time: 115, text: 'Peaceful stories waiting to unfold' },
    ],
    es: [
      { time: 0, text: '♪ (Bucle cálido de cinta y teclas suaves) ♪' },
      { time: 25, text: 'El lápiz raspa sobre la página de papel' },
      { time: 55, text: 'Los pensamientos se alejan lentamente' },
      { time: 85, text: 'El café en la taza se está enfriando' },
      { time: 115, text: 'Historias serenas esperando desplegarse' },
    ],
    tl: [
      { time: 0, text: '♪ (Mainit na tape loop at malamyang tipa) ♪' },
      { time: 25, text: 'Lapis na sumusulat sa pahina ng papel' },
      { time: 55, text: 'Mga iniisip ay dahan-dahang lumulutang' },
      { time: 85, text: 'Lumalamig na ang kape sa tasa' },
      { time: 115, text: 'Payapang kwento na naghihintay magbukas' },
    ],
    ja: [
      { time: 0, text: '♪ (温もりあるテープループと柔らかな鍵盤) ♪' },
      { time: 25, text: 'ノートの上を走る鉛筆の音' },
      { time: 55, text: '思考はふわりと空へと漂い' },
      { time: 85, text: 'マグカップのコーヒーは冷めていく' },
      { time: 115, text: '穏やかな物語が静かに開かれていく' },
    ],
    fr: [
      { time: 0, text: '♪ (Boucle de bande chaude et touches feutrées) ♪' },
      { time: 25, text: 'Le crayon glisse sur la feuille blanche' },
      { time: 55, text: "L'esprit s'évade au fil des heures" },
      { time: 85, text: 'Le café dans la tasse commence à refroidir' },
      { time: 115, text: 'De paisibles récits prêts à éclore' },
    ],
    de: [
      { time: 0, text: '♪ (Warme Bandschleife und sanfte Tasten) ♪' },
      { time: 25, text: 'Bleistift kratzt leise über das Papier' },
      { time: 55, text: 'Gedanken schweifen friedlich davon' },
      { time: 85, text: 'Der Kaffee in der Tasse wird langsam kalt' },
      { time: 115, text: 'Ruhige Geschichten warten darauf, erzählt zu werden' },
    ],
    ko: [
      { time: 0, text: '♪ (따스한 테이프 루프와 감미로운 건반) ♪' },
      { time: 25, text: '종이 위를 사각사각 스치는 연필 소리' },
      { time: 55, text: '생각들은 어느새 먼 곳으로 유영하고' },
      { time: 85, text: '머그잔 속 커피는 조금씩 식어가네' },
      { time: 115, text: '조용히 펼쳐지는 평화로운 이야기들' },
    ],
  },

  // 12. Ocean Breeze - Coastal Waves
  'song-ocean-breeze': {
    en: [
      { time: 0, text: '♪ (Gentle ocean waves crashing on the shore) ♪' },
      { time: 25, text: 'Salt in the air, wind through the hair' },
      { time: 55, text: 'Leaving behind every single care' },
      { time: 85, text: 'Endless horizon painted in blue' },
      { time: 115, text: 'Everything feels completely brand new' },
    ],
    es: [
      { time: 0, text: '♪ (Olas suaves del océano rompiendo en la orilla) ♪' },
      { time: 25, text: 'Sal en el aire, el viento en el cabello' },
      { time: 55, text: 'Dejando atrás cada preocupación' },
      { time: 85, text: 'Horizonte infinito pintado de azul' },
      { time: 115, text: 'Todo se siente completamente nuevo' },
    ],
    tl: [
      { time: 0, text: '♪ (Banayad na alon sa dalampasigan) ♪' },
      { time: 25, text: 'Asin sa hangin, simoy sa buhok' },
      { time: 55, text: 'Iniiwan ang bawat alalahanin' },
      { time: 85, text: 'Walang hanggang abot-tanaw na kulay asul' },
      { time: 115, text: 'Lahat ay tila bago at payapa' },
    ],
    ja: [
      { time: 0, text: '♪ (寄せては返す穏やかな波音) ♪' },
      { time: 25, text: '潮風の香り、髪をなでる優しい風' },
      { time: 55, text: 'すべての悩みごとを波間に残して' },
      { time: 85, text: '青一面に染まるどこまでも続く水平線' },
      { time: 115, text: 'すべてが新しく生まれ変わっていく' },
    ],
    fr: [
      { time: 0, text: '♪ (Douces vagues de l’océan caressant le rivage) ♪' },
      { time: 25, text: "L'odeur du sel, le vent dans les cheveux" },
      { time: 55, text: 'Laissant derrière soi chaque souci' },
      { time: 85, text: "Un horizon infini peint d'azur" },
      { time: 115, text: 'Tout semble renaître à nouveau' },
    ],
    de: [
      { time: 0, text: '♪ (Sanfte Meereswellen brechen am Ufer) ♪' },
      { time: 25, text: 'Salz in der Luft, Wind im Haar' },
      { time: 55, text: 'Lassen jede einzelne Sorge hinter uns' },
      { time: 85, text: 'Endloser Horizont in tiefem Blau' },
      { time: 115, text: 'Alles fühlt sich völlig neu an' },
    ],
    ko: [
      { time: 0, text: '♪ (해변가에 부서지는 잔잔한 파도 소리) ♪' },
      { time: 25, text: '공기 중에 밴 갯내음, 머리칼을 스치는 바람' },
      { time: 55, text: '모든 걱정과 시름은 저 뒤편에 둔 채' },
      { time: 85, text: '푸른빛으로 물든 끝없는 수평선' },
      { time: 115, text: '모든 것이 새롭게 태어난 듯 상쾌해' },
    ],
  },

  // 13. Whispering Pines - Timberland
  'song-whispering-pines': {
    en: [
      { time: 0, text: '♪ (Warm acoustic fingerpicking intro) ♪' },
      { time: 25, text: 'Sunlight filtering through the green canopy' },
      { time: 55, text: 'Walking slow in nature\'s harmony' },
      { time: 85, text: 'Pine needles softly under each stride' },
      { time: 115, text: 'Finding that peace we carry inside' },
    ],
    es: [
      { time: 0, text: '♪ (Cálido arpegio acústico) ♪' },
      { time: 25, text: 'La luz solar se filtra por la copa de los árboles' },
      { time: 55, text: 'Caminando despacio en la armonía del bosque' },
      { time: 85, text: 'Agujas de pino crujen suavemente bajo cada paso' },
      { time: 115, text: 'Encontrando la paz que llevamos dentro' },
    ],
    tl: [
      { time: 0, text: '♪ (Mainit na pagtugtog ng akustikong gitara) ♪' },
      { time: 25, text: 'Sinag ng araw na tumatagos sa mga dahon' },
      { time: 55, text: 'Mabagal na naglalakad sa himig ng kalikasan' },
      { time: 85, text: 'Dahon ng pino sa ilalim ng bawat hakbang' },
      { time: 115, text: 'Natatagpuan ang kapayapaan sa ating puso' },
    ],
    ja: [
      { time: 0, text: '♪ (温かいアコースティックの指弾き) ♪' },
      { time: 25, text: '木漏れ日が梢の間から降り注ぐ' },
      { time: 55, text: '自然の調和の中、ゆっくりと歩みを進める' },
      { time: 85, text: '一歩ごとに優しく踏みしめる松の葉' },
      { time: 115, text: '心の中に眠っていた静けさを取り戻していく' },
    ],
    fr: [
      { time: 0, text: '♪ (Arpèges acoustiques chaleureux aux doigts) ♪' },
      { time: 25, text: 'La lumière du soleil filtre à travers la canopée' },
      { time: 55, text: "Marchant doucement dans l'harmonie de la nature" },
      { time: 85, text: 'Aiguilles de pin sous chacun de nos pas' },
      { time: 115, text: 'Retrouvant la paix que nous portons en nous' },
    ],
    de: [
      { time: 0, text: '♪ (Warmes akustisches Fingerpicking) ♪' },
      { time: 25, text: 'Sonnenlicht bricht durch das grüne Blätterdach' },
      { time: 55, text: 'Langsam wandern im Einklang mit der Natur' },
      { time: 85, text: 'Kiefernadeln federn sanft unter jedem Schritt' },
      { time: 115, text: 'Den Frieden finden, den wir in uns tragen' },
    ],
    ko: [
      { time: 0, text: '♪ (따스한 어쿠스틱 핑거피킹 인트로) ♪' },
      { time: 25, text: '초록빛 나뭇가지 사이로 스며드는 햇살' },
      { time: 55, text: '자연의 숨결 속을 천천히 걸어가' },
      { time: 85, text: '발걸음마다 사뿐히 밟히는 솔잎들' },
      { time: 115, text: '마음 깊은 곳에 품고 있던 평화를 마주하네' },
    ],
  },

  // 14. Dancing Alone - Echo Chamber
  'song-dancing-alone': {
    en: [
      { time: 0, text: '♪ (Deep reverb drums and shimmering synth) ♪' },
      { time: 25, text: 'Shadows sway across the empty floor' },
      { time: 55, text: 'No need for anyone anymore' },
      { time: 85, text: 'Spun in circles in the twilight haze' },
      { time: 115, text: 'Lost forever in a rhythm maze' },
    ],
    es: [
      { time: 0, text: '♪ (Batería con profunda reverberación y sintetizador) ♪' },
      { time: 25, text: 'Las sombras se mecen en la pista vacía' },
      { time: 55, text: 'Ya no necesito a nadie más' },
      { time: 85, text: 'Girando en círculos en la niebla del atardecer' },
      { time: 115, text: 'Perdido para siempre en un laberinto de ritmos' },
    ],
    tl: [
      { time: 0, text: '♪ (Malalim na tambol at kumikinang na synth) ♪' },
      { time: 25, text: 'Mga anino ay sumasayaw sa walang lamang sahig' },
      { time: 55, text: 'Hindi na kailangan ng kahit sino pa' },
      { time: 85, text: 'Umiikot sa hamog ng dapit-hapon' },
      { time: 115, text: 'Naliligaw sa labirinto ng tugtugin' },
    ],
    ja: [
      { time: 0, text: '♪ (深いリバーブのドラムと煌めくシンセ) ♪' },
      { time: 25, text: '誰もいないフロアに揺れる影' },
      { time: 55, text: 'もう誰かの瞳を気にする必要はない' },
      { time: 85, text: '薄暮の霞の中でくるくると回り' },
      { time: 115, text: 'リズムの迷宮へと溶けていく' },
    ],
    fr: [
      { time: 0, text: '♪ (Batterie à profonde réverbération et synthé scintillant) ♪' },
      { time: 25, text: 'Les ombres ondulent sur la piste déserte' },
      { time: 55, text: "Plus besoin de personne à présent" },
      { time: 85, text: "Tournoyant dans la brume du crépuscule" },
      { time: 115, text: 'Égaré à jamais dans un dédale de rythmes' },
    ],
    de: [
      { time: 0, text: '♪ (Tiefer Hall auf den Trommeln und schimmernder Synth) ♪' },
      { time: 25, text: 'Schatten wiegen sich auf dem leeren Boden' },
      { time: 55, text: 'Brauche niemanden mehr an meiner Seite' },
      { time: 85, text: 'Drehe mich im Kreis im Zwielichtdunst' },
      { time: 115, text: 'Für immer verloren im Rhythmus-Labyrinth' },
    ],
    ko: [
      { time: 0, text: '♪ (깊은 리버브 드럼과 은은한 신스 선율) ♪' },
      { time: 25, text: '텅 빈 플로어 위로 일렁이는 그림자들' },
      { time: 55, text: '더 이상 그 누구도 필요치 않아' },
      { time: 85, text: '황혼의 아지랑이 속에서 빙글빙글 돌며' },
      { time: 115, text: '리듬의 미로 속에 영원히 빠져드네' },
    ],
  },
};
